// Code generated by ent, DO NOT EDIT.

package providersettlement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
)

const (
	// Label holds the string label denoting the providersettlement type in the database.
	Label = "provider_settlement"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProviderUserID holds the string denoting the provider_user_id field in the database.
	FieldProviderUserID = "provider_user_id"
	// FieldPeriodStart holds the string denoting the period_start field in the database.
	FieldPeriodStart = "period_start"
	// FieldPeriodEnd holds the string denoting the period_end field in the database.
	FieldPeriodEnd = "period_end"
	// FieldStandardCost holds the string denoting the standard_cost field in the database.
	FieldStandardCost = "standard_cost"
	// FieldRequests holds the string denoting the requests field in the database.
	FieldRequests = "requests"
	// FieldTokens holds the string denoting the tokens field in the database.
	FieldTokens = "tokens"
	// FieldAccountCount holds the string denoting the account_count field in the database.
	FieldAccountCount = "account_count"
	// FieldLastUsageID holds the string denoting the last_usage_id field in the database.
	FieldLastUsageID = "last_usage_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSettledAt holds the string denoting the settled_at field in the database.
	FieldSettledAt = "settled_at"
	// FieldSettledBy holds the string denoting the settled_by field in the database.
	FieldSettledBy = "settled_by"
	// FieldVoidedAt holds the string denoting the voided_at field in the database.
	FieldVoidedAt = "voided_at"
	// FieldVoidedBy holds the string denoting the voided_by field in the database.
	FieldVoidedBy = "voided_by"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldVoidReason holds the string denoting the void_reason field in the database.
	FieldVoidReason = "void_reason"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the providersettlement in the database.
	Table = "provider_settlements"
)

// Columns holds all SQL columns for providersettlement fields.
var Columns = []string{
	FieldID,
	FieldProviderUserID,
	FieldPeriodStart,
	FieldPeriodEnd,
	FieldStandardCost,
	FieldRequests,
	FieldTokens,
	FieldAccountCount,
	FieldLastUsageID,
	FieldStatus,
	FieldSettledAt,
	FieldSettledBy,
	FieldVoidedAt,
	FieldVoidedBy,
	FieldNotes,
	FieldVoidReason,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStandardCost holds the default value on creation for the "standard_cost" field.
	DefaultStandardCost func() decimal.Decimal
	// DefaultRequests holds the default value on creation for the "requests" field.
	DefaultRequests int64
	// DefaultTokens holds the default value on creation for the "tokens" field.
	DefaultTokens int64
	// DefaultAccountCount holds the default value on creation for the "account_count" field.
	DefaultAccountCount int
	// DefaultLastUsageID holds the default value on creation for the "last_usage_id" field.
	DefaultLastUsageID int64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultSettledAt holds the default value on creation for the "settled_at" field.
	DefaultSettledAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ProviderSettlement queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProviderUserID orders the results by the provider_user_id field.
func ByProviderUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderUserID, opts...).ToFunc()
}

// ByPeriodStart orders the results by the period_start field.
func ByPeriodStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodStart, opts...).ToFunc()
}

// ByPeriodEnd orders the results by the period_end field.
func ByPeriodEnd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeriodEnd, opts...).ToFunc()
}

// ByStandardCost orders the results by the standard_cost field.
func ByStandardCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStandardCost, opts...).ToFunc()
}

// ByRequests orders the results by the requests field.
func ByRequests(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequests, opts...).ToFunc()
}

// ByTokens orders the results by the tokens field.
func ByTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokens, opts...).ToFunc()
}

// ByAccountCount orders the results by the account_count field.
func ByAccountCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountCount, opts...).ToFunc()
}

// ByLastUsageID orders the results by the last_usage_id field.
func ByLastUsageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastUsageID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySettledAt orders the results by the settled_at field.
func BySettledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledAt, opts...).ToFunc()
}

// BySettledBy orders the results by the settled_by field.
func BySettledBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledBy, opts...).ToFunc()
}

// ByVoidedAt orders the results by the voided_at field.
func ByVoidedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVoidedAt, opts...).ToFunc()
}

// ByVoidedBy orders the results by the voided_by field.
func ByVoidedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVoidedBy, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByVoidReason orders the results by the void_reason field.
func ByVoidReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVoidReason, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
