// Code generated by ent, DO NOT EDIT.

package providersettlement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLTE(FieldID, id))
}

// ProviderUserID applies equality check predicate on the "provider_user_id" field. It's identical to ProviderUserIDEQ.
func ProviderUserID(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldProviderUserID, v))
}

// PeriodStart applies equality check predicate on the "period_start" field. It's identical to PeriodStartEQ.
func PeriodStart(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodEnd applies equality check predicate on the "period_end" field. It's identical to PeriodEndEQ.
func PeriodEnd(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldPeriodEnd, v))
}

// StandardCost applies equality check predicate on the "standard_cost" field. It's identical to StandardCostEQ.
func StandardCost(v decimal.Decimal) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldStandardCost, v))
}

// Requests applies equality check predicate on the "requests" field. It's identical to RequestsEQ.
func Requests(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldRequests, v))
}

// Tokens applies equality check predicate on the "tokens" field. It's identical to TokensEQ.
func Tokens(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldTokens, v))
}

// AccountCount applies equality check predicate on the "account_count" field. It's identical to AccountCountEQ.
func AccountCount(v int) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldAccountCount, v))
}

// LastUsageID applies equality check predicate on the "last_usage_id" field. It's identical to LastUsageIDEQ.
func LastUsageID(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldLastUsageID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldStatus, v))
}

// SettledAt applies equality check predicate on the "settled_at" field. It's identical to SettledAtEQ.
func SettledAt(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldSettledAt, v))
}

// SettledBy applies equality check predicate on the "settled_by" field. It's identical to SettledByEQ.
func SettledBy(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldSettledBy, v))
}

// VoidedAt applies equality check predicate on the "voided_at" field. It's identical to VoidedAtEQ.
func VoidedAt(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldVoidedAt, v))
}

// VoidedBy applies equality check predicate on the "voided_by" field. It's identical to VoidedByEQ.
func VoidedBy(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldVoidedBy, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldNotes, v))
}

// VoidReason applies equality check predicate on the "void_reason" field. It's identical to VoidReasonEQ.
func VoidReason(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldVoidReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldCreatedAt, v))
}

// ProviderUserIDEQ applies the EQ predicate on the "provider_user_id" field.
func ProviderUserIDEQ(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldProviderUserID, v))
}

// ProviderUserIDNEQ applies the NEQ predicate on the "provider_user_id" field.
func ProviderUserIDNEQ(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNEQ(FieldProviderUserID, v))
}

// ProviderUserIDIn applies the In predicate on the "provider_user_id" field.
func ProviderUserIDIn(vs ...int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIn(FieldProviderUserID, vs...))
}

// ProviderUserIDNotIn applies the NotIn predicate on the "provider_user_id" field.
func ProviderUserIDNotIn(vs ...int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotIn(FieldProviderUserID, vs...))
}

// ProviderUserIDGT applies the GT predicate on the "provider_user_id" field.
func ProviderUserIDGT(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGT(FieldProviderUserID, v))
}

// ProviderUserIDGTE applies the GTE predicate on the "provider_user_id" field.
func ProviderUserIDGTE(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGTE(FieldProviderUserID, v))
}

// ProviderUserIDLT applies the LT predicate on the "provider_user_id" field.
func ProviderUserIDLT(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLT(FieldProviderUserID, v))
}

// ProviderUserIDLTE applies the LTE predicate on the "provider_user_id" field.
func ProviderUserIDLTE(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLTE(FieldProviderUserID, v))
}

// PeriodStartEQ applies the EQ predicate on the "period_start" field.
func PeriodStartEQ(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodStartNEQ applies the NEQ predicate on the "period_start" field.
func PeriodStartNEQ(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNEQ(FieldPeriodStart, v))
}

// PeriodStartIn applies the In predicate on the "period_start" field.
func PeriodStartIn(vs ...time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIn(FieldPeriodStart, vs...))
}

// PeriodStartNotIn applies the NotIn predicate on the "period_start" field.
func PeriodStartNotIn(vs ...time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotIn(FieldPeriodStart, vs...))
}

// PeriodStartGT applies the GT predicate on the "period_start" field.
func PeriodStartGT(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGT(FieldPeriodStart, v))
}

// PeriodStartGTE applies the GTE predicate on the "period_start" field.
func PeriodStartGTE(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGTE(FieldPeriodStart, v))
}

// PeriodStartLT applies the LT predicate on the "period_start" field.
func PeriodStartLT(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLT(FieldPeriodStart, v))
}

// PeriodStartLTE applies the LTE predicate on the "period_start" field.
func PeriodStartLTE(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLTE(FieldPeriodStart, v))
}

// PeriodEndEQ applies the EQ predicate on the "period_end" field.
func PeriodEndEQ(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldPeriodEnd, v))
}

// PeriodEndNEQ applies the NEQ predicate on the "period_end" field.
func PeriodEndNEQ(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNEQ(FieldPeriodEnd, v))
}

// PeriodEndIn applies the In predicate on the "period_end" field.
func PeriodEndIn(vs ...time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIn(FieldPeriodEnd, vs...))
}

// PeriodEndNotIn applies the NotIn predicate on the "period_end" field.
func PeriodEndNotIn(vs ...time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotIn(FieldPeriodEnd, vs...))
}

// PeriodEndGT applies the GT predicate on the "period_end" field.
func PeriodEndGT(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGT(FieldPeriodEnd, v))
}

// PeriodEndGTE applies the GTE predicate on the "period_end" field.
func PeriodEndGTE(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGTE(FieldPeriodEnd, v))
}

// PeriodEndLT applies the LT predicate on the "period_end" field.
func PeriodEndLT(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLT(FieldPeriodEnd, v))
}

// PeriodEndLTE applies the LTE predicate on the "period_end" field.
func PeriodEndLTE(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLTE(FieldPeriodEnd, v))
}

// StandardCostEQ applies the EQ predicate on the "standard_cost" field.
func StandardCostEQ(v decimal.Decimal) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldStandardCost, v))
}

// StandardCostNEQ applies the NEQ predicate on the "standard_cost" field.
func StandardCostNEQ(v decimal.Decimal) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNEQ(FieldStandardCost, v))
}

// StandardCostIn applies the In predicate on the "standard_cost" field.
func StandardCostIn(vs ...decimal.Decimal) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIn(FieldStandardCost, vs...))
}

// StandardCostNotIn applies the NotIn predicate on the "standard_cost" field.
func StandardCostNotIn(vs ...decimal.Decimal) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotIn(FieldStandardCost, vs...))
}

// StandardCostGT applies the GT predicate on the "standard_cost" field.
func StandardCostGT(v decimal.Decimal) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGT(FieldStandardCost, v))
}

// StandardCostGTE applies the GTE predicate on the "standard_cost" field.
func StandardCostGTE(v decimal.Decimal) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGTE(FieldStandardCost, v))
}

// StandardCostLT applies the LT predicate on the "standard_cost" field.
func StandardCostLT(v decimal.Decimal) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLT(FieldStandardCost, v))
}

// StandardCostLTE applies the LTE predicate on the "standard_cost" field.
func StandardCostLTE(v decimal.Decimal) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLTE(FieldStandardCost, v))
}

// RequestsEQ applies the EQ predicate on the "requests" field.
func RequestsEQ(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldRequests, v))
}

// RequestsNEQ applies the NEQ predicate on the "requests" field.
func RequestsNEQ(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNEQ(FieldRequests, v))
}

// RequestsIn applies the In predicate on the "requests" field.
func RequestsIn(vs ...int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIn(FieldRequests, vs...))
}

// RequestsNotIn applies the NotIn predicate on the "requests" field.
func RequestsNotIn(vs ...int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotIn(FieldRequests, vs...))
}

// RequestsGT applies the GT predicate on the "requests" field.
func RequestsGT(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGT(FieldRequests, v))
}

// RequestsGTE applies the GTE predicate on the "requests" field.
func RequestsGTE(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGTE(FieldRequests, v))
}

// RequestsLT applies the LT predicate on the "requests" field.
func RequestsLT(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLT(FieldRequests, v))
}

// RequestsLTE applies the LTE predicate on the "requests" field.
func RequestsLTE(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLTE(FieldRequests, v))
}

// TokensEQ applies the EQ predicate on the "tokens" field.
func TokensEQ(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldTokens, v))
}

// TokensNEQ applies the NEQ predicate on the "tokens" field.
func TokensNEQ(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNEQ(FieldTokens, v))
}

// TokensIn applies the In predicate on the "tokens" field.
func TokensIn(vs ...int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIn(FieldTokens, vs...))
}

// TokensNotIn applies the NotIn predicate on the "tokens" field.
func TokensNotIn(vs ...int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotIn(FieldTokens, vs...))
}

// TokensGT applies the GT predicate on the "tokens" field.
func TokensGT(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGT(FieldTokens, v))
}

// TokensGTE applies the GTE predicate on the "tokens" field.
func TokensGTE(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGTE(FieldTokens, v))
}

// TokensLT applies the LT predicate on the "tokens" field.
func TokensLT(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLT(FieldTokens, v))
}

// TokensLTE applies the LTE predicate on the "tokens" field.
func TokensLTE(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLTE(FieldTokens, v))
}

// AccountCountEQ applies the EQ predicate on the "account_count" field.
func AccountCountEQ(v int) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldAccountCount, v))
}

// AccountCountNEQ applies the NEQ predicate on the "account_count" field.
func AccountCountNEQ(v int) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNEQ(FieldAccountCount, v))
}

// AccountCountIn applies the In predicate on the "account_count" field.
func AccountCountIn(vs ...int) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIn(FieldAccountCount, vs...))
}

// AccountCountNotIn applies the NotIn predicate on the "account_count" field.
func AccountCountNotIn(vs ...int) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotIn(FieldAccountCount, vs...))
}

// AccountCountGT applies the GT predicate on the "account_count" field.
func AccountCountGT(v int) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGT(FieldAccountCount, v))
}

// AccountCountGTE applies the GTE predicate on the "account_count" field.
func AccountCountGTE(v int) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGTE(FieldAccountCount, v))
}

// AccountCountLT applies the LT predicate on the "account_count" field.
func AccountCountLT(v int) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLT(FieldAccountCount, v))
}

// AccountCountLTE applies the LTE predicate on the "account_count" field.
func AccountCountLTE(v int) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLTE(FieldAccountCount, v))
}

// LastUsageIDEQ applies the EQ predicate on the "last_usage_id" field.
func LastUsageIDEQ(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldLastUsageID, v))
}

// LastUsageIDNEQ applies the NEQ predicate on the "last_usage_id" field.
func LastUsageIDNEQ(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNEQ(FieldLastUsageID, v))
}

// LastUsageIDIn applies the In predicate on the "last_usage_id" field.
func LastUsageIDIn(vs ...int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIn(FieldLastUsageID, vs...))
}

// LastUsageIDNotIn applies the NotIn predicate on the "last_usage_id" field.
func LastUsageIDNotIn(vs ...int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotIn(FieldLastUsageID, vs...))
}

// LastUsageIDGT applies the GT predicate on the "last_usage_id" field.
func LastUsageIDGT(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGT(FieldLastUsageID, v))
}

// LastUsageIDGTE applies the GTE predicate on the "last_usage_id" field.
func LastUsageIDGTE(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGTE(FieldLastUsageID, v))
}

// LastUsageIDLT applies the LT predicate on the "last_usage_id" field.
func LastUsageIDLT(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLT(FieldLastUsageID, v))
}

// LastUsageIDLTE applies the LTE predicate on the "last_usage_id" field.
func LastUsageIDLTE(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLTE(FieldLastUsageID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldContainsFold(FieldStatus, v))
}

// SettledAtEQ applies the EQ predicate on the "settled_at" field.
func SettledAtEQ(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldSettledAt, v))
}

// SettledAtNEQ applies the NEQ predicate on the "settled_at" field.
func SettledAtNEQ(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNEQ(FieldSettledAt, v))
}

// SettledAtIn applies the In predicate on the "settled_at" field.
func SettledAtIn(vs ...time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIn(FieldSettledAt, vs...))
}

// SettledAtNotIn applies the NotIn predicate on the "settled_at" field.
func SettledAtNotIn(vs ...time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotIn(FieldSettledAt, vs...))
}

// SettledAtGT applies the GT predicate on the "settled_at" field.
func SettledAtGT(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGT(FieldSettledAt, v))
}

// SettledAtGTE applies the GTE predicate on the "settled_at" field.
func SettledAtGTE(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGTE(FieldSettledAt, v))
}

// SettledAtLT applies the LT predicate on the "settled_at" field.
func SettledAtLT(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLT(FieldSettledAt, v))
}

// SettledAtLTE applies the LTE predicate on the "settled_at" field.
func SettledAtLTE(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLTE(FieldSettledAt, v))
}

// SettledByEQ applies the EQ predicate on the "settled_by" field.
func SettledByEQ(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldSettledBy, v))
}

// SettledByNEQ applies the NEQ predicate on the "settled_by" field.
func SettledByNEQ(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNEQ(FieldSettledBy, v))
}

// SettledByIn applies the In predicate on the "settled_by" field.
func SettledByIn(vs ...int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIn(FieldSettledBy, vs...))
}

// SettledByNotIn applies the NotIn predicate on the "settled_by" field.
func SettledByNotIn(vs ...int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotIn(FieldSettledBy, vs...))
}

// SettledByGT applies the GT predicate on the "settled_by" field.
func SettledByGT(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGT(FieldSettledBy, v))
}

// SettledByGTE applies the GTE predicate on the "settled_by" field.
func SettledByGTE(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGTE(FieldSettledBy, v))
}

// SettledByLT applies the LT predicate on the "settled_by" field.
func SettledByLT(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLT(FieldSettledBy, v))
}

// SettledByLTE applies the LTE predicate on the "settled_by" field.
func SettledByLTE(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLTE(FieldSettledBy, v))
}

// SettledByIsNil applies the IsNil predicate on the "settled_by" field.
func SettledByIsNil() predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIsNull(FieldSettledBy))
}

// SettledByNotNil applies the NotNil predicate on the "settled_by" field.
func SettledByNotNil() predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotNull(FieldSettledBy))
}

// VoidedAtEQ applies the EQ predicate on the "voided_at" field.
func VoidedAtEQ(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldVoidedAt, v))
}

// VoidedAtNEQ applies the NEQ predicate on the "voided_at" field.
func VoidedAtNEQ(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNEQ(FieldVoidedAt, v))
}

// VoidedAtIn applies the In predicate on the "voided_at" field.
func VoidedAtIn(vs ...time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIn(FieldVoidedAt, vs...))
}

// VoidedAtNotIn applies the NotIn predicate on the "voided_at" field.
func VoidedAtNotIn(vs ...time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotIn(FieldVoidedAt, vs...))
}

// VoidedAtGT applies the GT predicate on the "voided_at" field.
func VoidedAtGT(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGT(FieldVoidedAt, v))
}

// VoidedAtGTE applies the GTE predicate on the "voided_at" field.
func VoidedAtGTE(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGTE(FieldVoidedAt, v))
}

// VoidedAtLT applies the LT predicate on the "voided_at" field.
func VoidedAtLT(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLT(FieldVoidedAt, v))
}

// VoidedAtLTE applies the LTE predicate on the "voided_at" field.
func VoidedAtLTE(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLTE(FieldVoidedAt, v))
}

// VoidedAtIsNil applies the IsNil predicate on the "voided_at" field.
func VoidedAtIsNil() predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIsNull(FieldVoidedAt))
}

// VoidedAtNotNil applies the NotNil predicate on the "voided_at" field.
func VoidedAtNotNil() predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotNull(FieldVoidedAt))
}

// VoidedByEQ applies the EQ predicate on the "voided_by" field.
func VoidedByEQ(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldVoidedBy, v))
}

// VoidedByNEQ applies the NEQ predicate on the "voided_by" field.
func VoidedByNEQ(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNEQ(FieldVoidedBy, v))
}

// VoidedByIn applies the In predicate on the "voided_by" field.
func VoidedByIn(vs ...int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIn(FieldVoidedBy, vs...))
}

// VoidedByNotIn applies the NotIn predicate on the "voided_by" field.
func VoidedByNotIn(vs ...int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotIn(FieldVoidedBy, vs...))
}

// VoidedByGT applies the GT predicate on the "voided_by" field.
func VoidedByGT(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGT(FieldVoidedBy, v))
}

// VoidedByGTE applies the GTE predicate on the "voided_by" field.
func VoidedByGTE(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGTE(FieldVoidedBy, v))
}

// VoidedByLT applies the LT predicate on the "voided_by" field.
func VoidedByLT(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLT(FieldVoidedBy, v))
}

// VoidedByLTE applies the LTE predicate on the "voided_by" field.
func VoidedByLTE(v int64) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLTE(FieldVoidedBy, v))
}

// VoidedByIsNil applies the IsNil predicate on the "voided_by" field.
func VoidedByIsNil() predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIsNull(FieldVoidedBy))
}

// VoidedByNotNil applies the NotNil predicate on the "voided_by" field.
func VoidedByNotNil() predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotNull(FieldVoidedBy))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldContainsFold(FieldNotes, v))
}

// VoidReasonEQ applies the EQ predicate on the "void_reason" field.
func VoidReasonEQ(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldVoidReason, v))
}

// VoidReasonNEQ applies the NEQ predicate on the "void_reason" field.
func VoidReasonNEQ(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNEQ(FieldVoidReason, v))
}

// VoidReasonIn applies the In predicate on the "void_reason" field.
func VoidReasonIn(vs ...string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIn(FieldVoidReason, vs...))
}

// VoidReasonNotIn applies the NotIn predicate on the "void_reason" field.
func VoidReasonNotIn(vs ...string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotIn(FieldVoidReason, vs...))
}

// VoidReasonGT applies the GT predicate on the "void_reason" field.
func VoidReasonGT(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGT(FieldVoidReason, v))
}

// VoidReasonGTE applies the GTE predicate on the "void_reason" field.
func VoidReasonGTE(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGTE(FieldVoidReason, v))
}

// VoidReasonLT applies the LT predicate on the "void_reason" field.
func VoidReasonLT(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLT(FieldVoidReason, v))
}

// VoidReasonLTE applies the LTE predicate on the "void_reason" field.
func VoidReasonLTE(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLTE(FieldVoidReason, v))
}

// VoidReasonContains applies the Contains predicate on the "void_reason" field.
func VoidReasonContains(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldContains(FieldVoidReason, v))
}

// VoidReasonHasPrefix applies the HasPrefix predicate on the "void_reason" field.
func VoidReasonHasPrefix(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldHasPrefix(FieldVoidReason, v))
}

// VoidReasonHasSuffix applies the HasSuffix predicate on the "void_reason" field.
func VoidReasonHasSuffix(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldHasSuffix(FieldVoidReason, v))
}

// VoidReasonIsNil applies the IsNil predicate on the "void_reason" field.
func VoidReasonIsNil() predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIsNull(FieldVoidReason))
}

// VoidReasonNotNil applies the NotNil predicate on the "void_reason" field.
func VoidReasonNotNil() predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotNull(FieldVoidReason))
}

// VoidReasonEqualFold applies the EqualFold predicate on the "void_reason" field.
func VoidReasonEqualFold(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEqualFold(FieldVoidReason, v))
}

// VoidReasonContainsFold applies the ContainsFold predicate on the "void_reason" field.
func VoidReasonContainsFold(v string) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldContainsFold(FieldVoidReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProviderSettlement) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProviderSettlement) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProviderSettlement) predicate.ProviderSettlement {
	return predicate.ProviderSettlement(sql.NotPredicates(p))
}
