// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/providersettlementitem"
	"github.com/shopspring/decimal"
)

// ProviderSettlementItem is the model entity for the ProviderSettlementItem schema.
type ProviderSettlementItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SettlementID holds the value of the "settlement_id" field.
	SettlementID int64 `json:"settlement_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// AccountName holds the value of the "account_name" field.
	AccountName string `json:"account_name,omitempty"`
	// Offline holds the value of the "offline" field.
	Offline bool `json:"offline,omitempty"`
	// Requests holds the value of the "requests" field.
	Requests int64 `json:"requests,omitempty"`
	// Tokens holds the value of the "tokens" field.
	Tokens int64 `json:"tokens,omitempty"`
	// StandardCost holds the value of the "standard_cost" field.
	StandardCost decimal.Decimal `json:"standard_cost,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProviderSettlementItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case providersettlementitem.FieldStandardCost:
			values[i] = new(decimal.Decimal)
		case providersettlementitem.FieldOffline:
			values[i] = new(sql.NullBool)
		case providersettlementitem.FieldID, providersettlementitem.FieldSettlementID, providersettlementitem.FieldAccountID, providersettlementitem.FieldRequests, providersettlementitem.FieldTokens:
			values[i] = new(sql.NullInt64)
		case providersettlementitem.FieldAccountName:
			values[i] = new(sql.NullString)
		case providersettlementitem.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProviderSettlementItem fields.
func (_m *ProviderSettlementItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case providersettlementitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case providersettlementitem.FieldSettlementID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field settlement_id", values[i])
			} else if value.Valid {
				_m.SettlementID = value.Int64
			}
		case providersettlementitem.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case providersettlementitem.FieldAccountName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field account_name", values[i])
			} else if value.Valid {
				_m.AccountName = value.String
			}
		case providersettlementitem.FieldOffline:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field offline", values[i])
			} else if value.Valid {
				_m.Offline = value.Bool
			}
		case providersettlementitem.FieldRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field requests", values[i])
			} else if value.Valid {
				_m.Requests = value.Int64
			}
		case providersettlementitem.FieldTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tokens", values[i])
			} else if value.Valid {
				_m.Tokens = value.Int64
			}
		case providersettlementitem.FieldStandardCost:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field standard_cost", values[i])
			} else if value != nil {
				_m.StandardCost = *value
			}
		case providersettlementitem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProviderSettlementItem.
// This includes values selected through modifiers, order, etc.
func (_m *ProviderSettlementItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProviderSettlementItem.
// Note that you need to call ProviderSettlementItem.Unwrap() before calling this method if this ProviderSettlementItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProviderSettlementItem) Update() *ProviderSettlementItemUpdateOne {
	return NewProviderSettlementItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProviderSettlementItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProviderSettlementItem) Unwrap() *ProviderSettlementItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProviderSettlementItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProviderSettlementItem) String() string {
	var builder strings.Builder
	builder.WriteString("ProviderSettlementItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("settlement_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SettlementID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("account_name=")
	builder.WriteString(_m.AccountName)
	builder.WriteString(", ")
	builder.WriteString("offline=")
	builder.WriteString(fmt.Sprintf("%v", _m.Offline))
	builder.WriteString(", ")
	builder.WriteString("requests=")
	builder.WriteString(fmt.Sprintf("%v", _m.Requests))
	builder.WriteString(", ")
	builder.WriteString("tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tokens))
	builder.WriteString(", ")
	builder.WriteString("standard_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.StandardCost))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProviderSettlementItems is a parsable slice of ProviderSettlementItem.
type ProviderSettlementItems []*ProviderSettlementItem
