// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/providersettlementitem"
	"github.com/shopspring/decimal"
)

// ProviderSettlementItemUpdate is the builder for updating ProviderSettlementItem entities.
type ProviderSettlementItemUpdate struct {
	config
	hooks    []Hook
	mutation *ProviderSettlementItemMutation
}

// Where appends a list predicates to the ProviderSettlementItemUpdate builder.
func (_u *ProviderSettlementItemUpdate) Where(ps ...predicate.ProviderSettlementItem) *ProviderSettlementItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSettlementID sets the "settlement_id" field.
func (_u *ProviderSettlementItemUpdate) SetSettlementID(v int64) *ProviderSettlementItemUpdate {
	_u.mutation.ResetSettlementID()
	_u.mutation.SetSettlementID(v)
	return _u
}

// SetNillableSettlementID sets the "settlement_id" field if the given value is not nil.
func (_u *ProviderSettlementItemUpdate) SetNillableSettlementID(v *int64) *ProviderSettlementItemUpdate {
	if v != nil {
		_u.SetSettlementID(*v)
	}
	return _u
}

// AddSettlementID adds value to the "settlement_id" field.
func (_u *ProviderSettlementItemUpdate) AddSettlementID(v int64) *ProviderSettlementItemUpdate {
	_u.mutation.AddSettlementID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ProviderSettlementItemUpdate) SetAccountID(v int64) *ProviderSettlementItemUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ProviderSettlementItemUpdate) SetNillableAccountID(v *int64) *ProviderSettlementItemUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *ProviderSettlementItemUpdate) AddAccountID(v int64) *ProviderSettlementItemUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetAccountName sets the "account_name" field.
func (_u *ProviderSettlementItemUpdate) SetAccountName(v string) *ProviderSettlementItemUpdate {
	_u.mutation.SetAccountName(v)
	return _u
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (_u *ProviderSettlementItemUpdate) SetNillableAccountName(v *string) *ProviderSettlementItemUpdate {
	if v != nil {
		_u.SetAccountName(*v)
	}
	return _u
}

// SetOffline sets the "offline" field.
func (_u *ProviderSettlementItemUpdate) SetOffline(v bool) *ProviderSettlementItemUpdate {
	_u.mutation.SetOffline(v)
	return _u
}

// SetNillableOffline sets the "offline" field if the given value is not nil.
func (_u *ProviderSettlementItemUpdate) SetNillableOffline(v *bool) *ProviderSettlementItemUpdate {
	if v != nil {
		_u.SetOffline(*v)
	}
	return _u
}

// SetRequests sets the "requests" field.
func (_u *ProviderSettlementItemUpdate) SetRequests(v int64) *ProviderSettlementItemUpdate {
	_u.mutation.ResetRequests()
	_u.mutation.SetRequests(v)
	return _u
}

// SetNillableRequests sets the "requests" field if the given value is not nil.
func (_u *ProviderSettlementItemUpdate) SetNillableRequests(v *int64) *ProviderSettlementItemUpdate {
	if v != nil {
		_u.SetRequests(*v)
	}
	return _u
}

// AddRequests adds value to the "requests" field.
func (_u *ProviderSettlementItemUpdate) AddRequests(v int64) *ProviderSettlementItemUpdate {
	_u.mutation.AddRequests(v)
	return _u
}

// SetTokens sets the "tokens" field.
func (_u *ProviderSettlementItemUpdate) SetTokens(v int64) *ProviderSettlementItemUpdate {
	_u.mutation.ResetTokens()
	_u.mutation.SetTokens(v)
	return _u
}

// SetNillableTokens sets the "tokens" field if the given value is not nil.
func (_u *ProviderSettlementItemUpdate) SetNillableTokens(v *int64) *ProviderSettlementItemUpdate {
	if v != nil {
		_u.SetTokens(*v)
	}
	return _u
}

// AddTokens adds value to the "tokens" field.
func (_u *ProviderSettlementItemUpdate) AddTokens(v int64) *ProviderSettlementItemUpdate {
	_u.mutation.AddTokens(v)
	return _u
}

// SetStandardCost sets the "standard_cost" field.
func (_u *ProviderSettlementItemUpdate) SetStandardCost(v decimal.Decimal) *ProviderSettlementItemUpdate {
	_u.mutation.ResetStandardCost()
	_u.mutation.SetStandardCost(v)
	return _u
}

// SetNillableStandardCost sets the "standard_cost" field if the given value is not nil.
func (_u *ProviderSettlementItemUpdate) SetNillableStandardCost(v *decimal.Decimal) *ProviderSettlementItemUpdate {
	if v != nil {
		_u.SetStandardCost(*v)
	}
	return _u
}

// AddStandardCost adds value to the "standard_cost" field.
func (_u *ProviderSettlementItemUpdate) AddStandardCost(v decimal.Decimal) *ProviderSettlementItemUpdate {
	_u.mutation.AddStandardCost(v)
	return _u
}

// Mutation returns the ProviderSettlementItemMutation object of the builder.
func (_u *ProviderSettlementItemUpdate) Mutation() *ProviderSettlementItemMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderSettlementItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderSettlementItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderSettlementItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderSettlementItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderSettlementItemUpdate) check() error {
	if v, ok := _u.mutation.AccountName(); ok {
		if err := providersettlementitem.AccountNameValidator(v); err != nil {
			return &ValidationError{Name: "account_name", err: fmt.Errorf(`ent: validator failed for field "ProviderSettlementItem.account_name": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderSettlementItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providersettlementitem.Table, providersettlementitem.Columns, sqlgraph.NewFieldSpec(providersettlementitem.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SettlementID(); ok {
		_spec.SetField(providersettlementitem.FieldSettlementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSettlementID(); ok {
		_spec.AddField(providersettlementitem.FieldSettlementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(providersettlementitem.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(providersettlementitem.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountName(); ok {
		_spec.SetField(providersettlementitem.FieldAccountName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Offline(); ok {
		_spec.SetField(providersettlementitem.FieldOffline, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Requests(); ok {
		_spec.SetField(providersettlementitem.FieldRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequests(); ok {
		_spec.AddField(providersettlementitem.FieldRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Tokens(); ok {
		_spec.SetField(providersettlementitem.FieldTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTokens(); ok {
		_spec.AddField(providersettlementitem.FieldTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StandardCost(); ok {
		_spec.SetField(providersettlementitem.FieldStandardCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStandardCost(); ok {
		_spec.AddField(providersettlementitem.FieldStandardCost, field.TypeFloat64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providersettlementitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderSettlementItemUpdateOne is the builder for updating a single ProviderSettlementItem entity.
type ProviderSettlementItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProviderSettlementItemMutation
}

// SetSettlementID sets the "settlement_id" field.
func (_u *ProviderSettlementItemUpdateOne) SetSettlementID(v int64) *ProviderSettlementItemUpdateOne {
	_u.mutation.ResetSettlementID()
	_u.mutation.SetSettlementID(v)
	return _u
}

// SetNillableSettlementID sets the "settlement_id" field if the given value is not nil.
func (_u *ProviderSettlementItemUpdateOne) SetNillableSettlementID(v *int64) *ProviderSettlementItemUpdateOne {
	if v != nil {
		_u.SetSettlementID(*v)
	}
	return _u
}

// AddSettlementID adds value to the "settlement_id" field.
func (_u *ProviderSettlementItemUpdateOne) AddSettlementID(v int64) *ProviderSettlementItemUpdateOne {
	_u.mutation.AddSettlementID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ProviderSettlementItemUpdateOne) SetAccountID(v int64) *ProviderSettlementItemUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ProviderSettlementItemUpdateOne) SetNillableAccountID(v *int64) *ProviderSettlementItemUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *ProviderSettlementItemUpdateOne) AddAccountID(v int64) *ProviderSettlementItemUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetAccountName sets the "account_name" field.
func (_u *ProviderSettlementItemUpdateOne) SetAccountName(v string) *ProviderSettlementItemUpdateOne {
	_u.mutation.SetAccountName(v)
	return _u
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (_u *ProviderSettlementItemUpdateOne) SetNillableAccountName(v *string) *ProviderSettlementItemUpdateOne {
	if v != nil {
		_u.SetAccountName(*v)
	}
	return _u
}

// SetOffline sets the "offline" field.
func (_u *ProviderSettlementItemUpdateOne) SetOffline(v bool) *ProviderSettlementItemUpdateOne {
	_u.mutation.SetOffline(v)
	return _u
}

// SetNillableOffline sets the "offline" field if the given value is not nil.
func (_u *ProviderSettlementItemUpdateOne) SetNillableOffline(v *bool) *ProviderSettlementItemUpdateOne {
	if v != nil {
		_u.SetOffline(*v)
	}
	return _u
}

// SetRequests sets the "requests" field.
func (_u *ProviderSettlementItemUpdateOne) SetRequests(v int64) *ProviderSettlementItemUpdateOne {
	_u.mutation.ResetRequests()
	_u.mutation.SetRequests(v)
	return _u
}

// SetNillableRequests sets the "requests" field if the given value is not nil.
func (_u *ProviderSettlementItemUpdateOne) SetNillableRequests(v *int64) *ProviderSettlementItemUpdateOne {
	if v != nil {
		_u.SetRequests(*v)
	}
	return _u
}

// AddRequests adds value to the "requests" field.
func (_u *ProviderSettlementItemUpdateOne) AddRequests(v int64) *ProviderSettlementItemUpdateOne {
	_u.mutation.AddRequests(v)
	return _u
}

// SetTokens sets the "tokens" field.
func (_u *ProviderSettlementItemUpdateOne) SetTokens(v int64) *ProviderSettlementItemUpdateOne {
	_u.mutation.ResetTokens()
	_u.mutation.SetTokens(v)
	return _u
}

// SetNillableTokens sets the "tokens" field if the given value is not nil.
func (_u *ProviderSettlementItemUpdateOne) SetNillableTokens(v *int64) *ProviderSettlementItemUpdateOne {
	if v != nil {
		_u.SetTokens(*v)
	}
	return _u
}

// AddTokens adds value to the "tokens" field.
func (_u *ProviderSettlementItemUpdateOne) AddTokens(v int64) *ProviderSettlementItemUpdateOne {
	_u.mutation.AddTokens(v)
	return _u
}

// SetStandardCost sets the "standard_cost" field.
func (_u *ProviderSettlementItemUpdateOne) SetStandardCost(v decimal.Decimal) *ProviderSettlementItemUpdateOne {
	_u.mutation.ResetStandardCost()
	_u.mutation.SetStandardCost(v)
	return _u
}

// SetNillableStandardCost sets the "standard_cost" field if the given value is not nil.
func (_u *ProviderSettlementItemUpdateOne) SetNillableStandardCost(v *decimal.Decimal) *ProviderSettlementItemUpdateOne {
	if v != nil {
		_u.SetStandardCost(*v)
	}
	return _u
}

// AddStandardCost adds value to the "standard_cost" field.
func (_u *ProviderSettlementItemUpdateOne) AddStandardCost(v decimal.Decimal) *ProviderSettlementItemUpdateOne {
	_u.mutation.AddStandardCost(v)
	return _u
}

// Mutation returns the ProviderSettlementItemMutation object of the builder.
func (_u *ProviderSettlementItemUpdateOne) Mutation() *ProviderSettlementItemMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProviderSettlementItemUpdate builder.
func (_u *ProviderSettlementItemUpdateOne) Where(ps ...predicate.ProviderSettlementItem) *ProviderSettlementItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderSettlementItemUpdateOne) Select(field string, fields ...string) *ProviderSettlementItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProviderSettlementItem entity.
func (_u *ProviderSettlementItemUpdateOne) Save(ctx context.Context) (*ProviderSettlementItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderSettlementItemUpdateOne) SaveX(ctx context.Context) *ProviderSettlementItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderSettlementItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderSettlementItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderSettlementItemUpdateOne) check() error {
	if v, ok := _u.mutation.AccountName(); ok {
		if err := providersettlementitem.AccountNameValidator(v); err != nil {
			return &ValidationError{Name: "account_name", err: fmt.Errorf(`ent: validator failed for field "ProviderSettlementItem.account_name": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderSettlementItemUpdateOne) sqlSave(ctx context.Context) (_node *ProviderSettlementItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providersettlementitem.Table, providersettlementitem.Columns, sqlgraph.NewFieldSpec(providersettlementitem.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProviderSettlementItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, providersettlementitem.FieldID)
		for _, f := range fields {
			if !providersettlementitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != providersettlementitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SettlementID(); ok {
		_spec.SetField(providersettlementitem.FieldSettlementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSettlementID(); ok {
		_spec.AddField(providersettlementitem.FieldSettlementID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(providersettlementitem.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(providersettlementitem.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountName(); ok {
		_spec.SetField(providersettlementitem.FieldAccountName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Offline(); ok {
		_spec.SetField(providersettlementitem.FieldOffline, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Requests(); ok {
		_spec.SetField(providersettlementitem.FieldRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequests(); ok {
		_spec.AddField(providersettlementitem.FieldRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Tokens(); ok {
		_spec.SetField(providersettlementitem.FieldTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTokens(); ok {
		_spec.AddField(providersettlementitem.FieldTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StandardCost(); ok {
		_spec.SetField(providersettlementitem.FieldStandardCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStandardCost(); ok {
		_spec.AddField(providersettlementitem.FieldStandardCost, field.TypeFloat64, value)
	}
	_node = &ProviderSettlementItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providersettlementitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
