// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/providersettlement"
	"github.com/shopspring/decimal"
)

// ProviderSettlement is the model entity for the ProviderSettlement schema.
type ProviderSettlement struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ProviderUserID holds the value of the "provider_user_id" field.
	ProviderUserID int64 `json:"provider_user_id,omitempty"`
	// PeriodStart holds the value of the "period_start" field.
	PeriodStart time.Time `json:"period_start,omitempty"`
	// PeriodEnd holds the value of the "period_end" field.
	PeriodEnd time.Time `json:"period_end,omitempty"`
	// StandardCost holds the value of the "standard_cost" field.
	StandardCost decimal.Decimal `json:"standard_cost,omitempty"`
	// Requests holds the value of the "requests" field.
	Requests int64 `json:"requests,omitempty"`
	// Tokens holds the value of the "tokens" field.
	Tokens int64 `json:"tokens,omitempty"`
	// AccountCount holds the value of the "account_count" field.
	AccountCount int `json:"account_count,omitempty"`
	// LastUsageID holds the value of the "last_usage_id" field.
	LastUsageID int64 `json:"last_usage_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// SettledAt holds the value of the "settled_at" field.
	SettledAt time.Time `json:"settled_at,omitempty"`
	// SettledBy holds the value of the "settled_by" field.
	SettledBy *int64 `json:"settled_by,omitempty"`
	// VoidedAt holds the value of the "voided_at" field.
	VoidedAt *time.Time `json:"voided_at,omitempty"`
	// VoidedBy holds the value of the "voided_by" field.
	VoidedBy *int64 `json:"voided_by,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// VoidReason holds the value of the "void_reason" field.
	VoidReason *string `json:"void_reason,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ProviderSettlement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case providersettlement.FieldStandardCost:
			values[i] = new(decimal.Decimal)
		case providersettlement.FieldID, providersettlement.FieldProviderUserID, providersettlement.FieldRequests, providersettlement.FieldTokens, providersettlement.FieldAccountCount, providersettlement.FieldLastUsageID, providersettlement.FieldSettledBy, providersettlement.FieldVoidedBy:
			values[i] = new(sql.NullInt64)
		case providersettlement.FieldStatus, providersettlement.FieldNotes, providersettlement.FieldVoidReason:
			values[i] = new(sql.NullString)
		case providersettlement.FieldPeriodStart, providersettlement.FieldPeriodEnd, providersettlement.FieldSettledAt, providersettlement.FieldVoidedAt, providersettlement.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ProviderSettlement fields.
func (_m *ProviderSettlement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case providersettlement.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case providersettlement.FieldProviderUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_user_id", values[i])
			} else if value.Valid {
				_m.ProviderUserID = value.Int64
			}
		case providersettlement.FieldPeriodStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field period_start", values[i])
			} else if value.Valid {
				_m.PeriodStart = value.Time
			}
		case providersettlement.FieldPeriodEnd:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field period_end", values[i])
			} else if value.Valid {
				_m.PeriodEnd = value.Time
			}
		case providersettlement.FieldStandardCost:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field standard_cost", values[i])
			} else if value != nil {
				_m.StandardCost = *value
			}
		case providersettlement.FieldRequests:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field requests", values[i])
			} else if value.Valid {
				_m.Requests = value.Int64
			}
		case providersettlement.FieldTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tokens", values[i])
			} else if value.Valid {
				_m.Tokens = value.Int64
			}
		case providersettlement.FieldAccountCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_count", values[i])
			} else if value.Valid {
				_m.AccountCount = int(value.Int64)
			}
		case providersettlement.FieldLastUsageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_usage_id", values[i])
			} else if value.Valid {
				_m.LastUsageID = value.Int64
			}
		case providersettlement.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case providersettlement.FieldSettledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field settled_at", values[i])
			} else if value.Valid {
				_m.SettledAt = value.Time
			}
		case providersettlement.FieldSettledBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field settled_by", values[i])
			} else if value.Valid {
				_m.SettledBy = new(int64)
				*_m.SettledBy = value.Int64
			}
		case providersettlement.FieldVoidedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field voided_at", values[i])
			} else if value.Valid {
				_m.VoidedAt = new(time.Time)
				*_m.VoidedAt = value.Time
			}
		case providersettlement.FieldVoidedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field voided_by", values[i])
			} else if value.Valid {
				_m.VoidedBy = new(int64)
				*_m.VoidedBy = value.Int64
			}
		case providersettlement.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case providersettlement.FieldVoidReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field void_reason", values[i])
			} else if value.Valid {
				_m.VoidReason = new(string)
				*_m.VoidReason = value.String
			}
		case providersettlement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ProviderSettlement.
// This includes values selected through modifiers, order, etc.
func (_m *ProviderSettlement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ProviderSettlement.
// Note that you need to call ProviderSettlement.Unwrap() before calling this method if this ProviderSettlement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ProviderSettlement) Update() *ProviderSettlementUpdateOne {
	return NewProviderSettlementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ProviderSettlement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ProviderSettlement) Unwrap() *ProviderSettlement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ProviderSettlement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ProviderSettlement) String() string {
	var builder strings.Builder
	builder.WriteString("ProviderSettlement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("provider_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderUserID))
	builder.WriteString(", ")
	builder.WriteString("period_start=")
	builder.WriteString(_m.PeriodStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("period_end=")
	builder.WriteString(_m.PeriodEnd.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("standard_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.StandardCost))
	builder.WriteString(", ")
	builder.WriteString("requests=")
	builder.WriteString(fmt.Sprintf("%v", _m.Requests))
	builder.WriteString(", ")
	builder.WriteString("tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tokens))
	builder.WriteString(", ")
	builder.WriteString("account_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountCount))
	builder.WriteString(", ")
	builder.WriteString("last_usage_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastUsageID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("settled_at=")
	builder.WriteString(_m.SettledAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.SettledBy; v != nil {
		builder.WriteString("settled_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.VoidedAt; v != nil {
		builder.WriteString("voided_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.VoidedBy; v != nil {
		builder.WriteString("voided_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.VoidReason; v != nil {
		builder.WriteString("void_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ProviderSettlements is a parsable slice of ProviderSettlement.
type ProviderSettlements []*ProviderSettlement
