// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/providersettlement"
	"github.com/shopspring/decimal"
)

// ProviderSettlementUpdate is the builder for updating ProviderSettlement entities.
type ProviderSettlementUpdate struct {
	config
	hooks    []Hook
	mutation *ProviderSettlementMutation
}

// Where appends a list predicates to the ProviderSettlementUpdate builder.
func (_u *ProviderSettlementUpdate) Where(ps ...predicate.ProviderSettlement) *ProviderSettlementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProviderUserID sets the "provider_user_id" field.
func (_u *ProviderSettlementUpdate) SetProviderUserID(v int64) *ProviderSettlementUpdate {
	_u.mutation.ResetProviderUserID()
	_u.mutation.SetProviderUserID(v)
	return _u
}

// SetNillableProviderUserID sets the "provider_user_id" field if the given value is not nil.
func (_u *ProviderSettlementUpdate) SetNillableProviderUserID(v *int64) *ProviderSettlementUpdate {
	if v != nil {
		_u.SetProviderUserID(*v)
	}
	return _u
}

// AddProviderUserID adds value to the "provider_user_id" field.
func (_u *ProviderSettlementUpdate) AddProviderUserID(v int64) *ProviderSettlementUpdate {
	_u.mutation.AddProviderUserID(v)
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *ProviderSettlementUpdate) SetPeriodStart(v time.Time) *ProviderSettlementUpdate {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *ProviderSettlementUpdate) SetNillablePeriodStart(v *time.Time) *ProviderSettlementUpdate {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// SetPeriodEnd sets the "period_end" field.
func (_u *ProviderSettlementUpdate) SetPeriodEnd(v time.Time) *ProviderSettlementUpdate {
	_u.mutation.SetPeriodEnd(v)
	return _u
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (_u *ProviderSettlementUpdate) SetNillablePeriodEnd(v *time.Time) *ProviderSettlementUpdate {
	if v != nil {
		_u.SetPeriodEnd(*v)
	}
	return _u
}

// SetStandardCost sets the "standard_cost" field.
func (_u *ProviderSettlementUpdate) SetStandardCost(v decimal.Decimal) *ProviderSettlementUpdate {
	_u.mutation.ResetStandardCost()
	_u.mutation.SetStandardCost(v)
	return _u
}

// SetNillableStandardCost sets the "standard_cost" field if the given value is not nil.
func (_u *ProviderSettlementUpdate) SetNillableStandardCost(v *decimal.Decimal) *ProviderSettlementUpdate {
	if v != nil {
		_u.SetStandardCost(*v)
	}
	return _u
}

// AddStandardCost adds value to the "standard_cost" field.
func (_u *ProviderSettlementUpdate) AddStandardCost(v decimal.Decimal) *ProviderSettlementUpdate {
	_u.mutation.AddStandardCost(v)
	return _u
}

// SetRequests sets the "requests" field.
func (_u *ProviderSettlementUpdate) SetRequests(v int64) *ProviderSettlementUpdate {
	_u.mutation.ResetRequests()
	_u.mutation.SetRequests(v)
	return _u
}

// SetNillableRequests sets the "requests" field if the given value is not nil.
func (_u *ProviderSettlementUpdate) SetNillableRequests(v *int64) *ProviderSettlementUpdate {
	if v != nil {
		_u.SetRequests(*v)
	}
	return _u
}

// AddRequests adds value to the "requests" field.
func (_u *ProviderSettlementUpdate) AddRequests(v int64) *ProviderSettlementUpdate {
	_u.mutation.AddRequests(v)
	return _u
}

// SetTokens sets the "tokens" field.
func (_u *ProviderSettlementUpdate) SetTokens(v int64) *ProviderSettlementUpdate {
	_u.mutation.ResetTokens()
	_u.mutation.SetTokens(v)
	return _u
}

// SetNillableTokens sets the "tokens" field if the given value is not nil.
func (_u *ProviderSettlementUpdate) SetNillableTokens(v *int64) *ProviderSettlementUpdate {
	if v != nil {
		_u.SetTokens(*v)
	}
	return _u
}

// AddTokens adds value to the "tokens" field.
func (_u *ProviderSettlementUpdate) AddTokens(v int64) *ProviderSettlementUpdate {
	_u.mutation.AddTokens(v)
	return _u
}

// SetAccountCount sets the "account_count" field.
func (_u *ProviderSettlementUpdate) SetAccountCount(v int) *ProviderSettlementUpdate {
	_u.mutation.ResetAccountCount()
	_u.mutation.SetAccountCount(v)
	return _u
}

// SetNillableAccountCount sets the "account_count" field if the given value is not nil.
func (_u *ProviderSettlementUpdate) SetNillableAccountCount(v *int) *ProviderSettlementUpdate {
	if v != nil {
		_u.SetAccountCount(*v)
	}
	return _u
}

// AddAccountCount adds value to the "account_count" field.
func (_u *ProviderSettlementUpdate) AddAccountCount(v int) *ProviderSettlementUpdate {
	_u.mutation.AddAccountCount(v)
	return _u
}

// SetLastUsageID sets the "last_usage_id" field.
func (_u *ProviderSettlementUpdate) SetLastUsageID(v int64) *ProviderSettlementUpdate {
	_u.mutation.ResetLastUsageID()
	_u.mutation.SetLastUsageID(v)
	return _u
}

// SetNillableLastUsageID sets the "last_usage_id" field if the given value is not nil.
func (_u *ProviderSettlementUpdate) SetNillableLastUsageID(v *int64) *ProviderSettlementUpdate {
	if v != nil {
		_u.SetLastUsageID(*v)
	}
	return _u
}

// AddLastUsageID adds value to the "last_usage_id" field.
func (_u *ProviderSettlementUpdate) AddLastUsageID(v int64) *ProviderSettlementUpdate {
	_u.mutation.AddLastUsageID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProviderSettlementUpdate) SetStatus(v string) *ProviderSettlementUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProviderSettlementUpdate) SetNillableStatus(v *string) *ProviderSettlementUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *ProviderSettlementUpdate) SetSettledAt(v time.Time) *ProviderSettlementUpdate {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *ProviderSettlementUpdate) SetNillableSettledAt(v *time.Time) *ProviderSettlementUpdate {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// SetSettledBy sets the "settled_by" field.
func (_u *ProviderSettlementUpdate) SetSettledBy(v int64) *ProviderSettlementUpdate {
	_u.mutation.ResetSettledBy()
	_u.mutation.SetSettledBy(v)
	return _u
}

// SetNillableSettledBy sets the "settled_by" field if the given value is not nil.
func (_u *ProviderSettlementUpdate) SetNillableSettledBy(v *int64) *ProviderSettlementUpdate {
	if v != nil {
		_u.SetSettledBy(*v)
	}
	return _u
}

// AddSettledBy adds value to the "settled_by" field.
func (_u *ProviderSettlementUpdate) AddSettledBy(v int64) *ProviderSettlementUpdate {
	_u.mutation.AddSettledBy(v)
	return _u
}

// ClearSettledBy clears the value of the "settled_by" field.
func (_u *ProviderSettlementUpdate) ClearSettledBy() *ProviderSettlementUpdate {
	_u.mutation.ClearSettledBy()
	return _u
}

// SetVoidedAt sets the "voided_at" field.
func (_u *ProviderSettlementUpdate) SetVoidedAt(v time.Time) *ProviderSettlementUpdate {
	_u.mutation.SetVoidedAt(v)
	return _u
}

// SetNillableVoidedAt sets the "voided_at" field if the given value is not nil.
func (_u *ProviderSettlementUpdate) SetNillableVoidedAt(v *time.Time) *ProviderSettlementUpdate {
	if v != nil {
		_u.SetVoidedAt(*v)
	}
	return _u
}

// ClearVoidedAt clears the value of the "voided_at" field.
func (_u *ProviderSettlementUpdate) ClearVoidedAt() *ProviderSettlementUpdate {
	_u.mutation.ClearVoidedAt()
	return _u
}

// SetVoidedBy sets the "voided_by" field.
func (_u *ProviderSettlementUpdate) SetVoidedBy(v int64) *ProviderSettlementUpdate {
	_u.mutation.ResetVoidedBy()
	_u.mutation.SetVoidedBy(v)
	return _u
}

// SetNillableVoidedBy sets the "voided_by" field if the given value is not nil.
func (_u *ProviderSettlementUpdate) SetNillableVoidedBy(v *int64) *ProviderSettlementUpdate {
	if v != nil {
		_u.SetVoidedBy(*v)
	}
	return _u
}

// AddVoidedBy adds value to the "voided_by" field.
func (_u *ProviderSettlementUpdate) AddVoidedBy(v int64) *ProviderSettlementUpdate {
	_u.mutation.AddVoidedBy(v)
	return _u
}

// ClearVoidedBy clears the value of the "voided_by" field.
func (_u *ProviderSettlementUpdate) ClearVoidedBy() *ProviderSettlementUpdate {
	_u.mutation.ClearVoidedBy()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ProviderSettlementUpdate) SetNotes(v string) *ProviderSettlementUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ProviderSettlementUpdate) SetNillableNotes(v *string) *ProviderSettlementUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *ProviderSettlementUpdate) ClearNotes() *ProviderSettlementUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetVoidReason sets the "void_reason" field.
func (_u *ProviderSettlementUpdate) SetVoidReason(v string) *ProviderSettlementUpdate {
	_u.mutation.SetVoidReason(v)
	return _u
}

// SetNillableVoidReason sets the "void_reason" field if the given value is not nil.
func (_u *ProviderSettlementUpdate) SetNillableVoidReason(v *string) *ProviderSettlementUpdate {
	if v != nil {
		_u.SetVoidReason(*v)
	}
	return _u
}

// ClearVoidReason clears the value of the "void_reason" field.
func (_u *ProviderSettlementUpdate) ClearVoidReason() *ProviderSettlementUpdate {
	_u.mutation.ClearVoidReason()
	return _u
}

// Mutation returns the ProviderSettlementMutation object of the builder.
func (_u *ProviderSettlementUpdate) Mutation() *ProviderSettlementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProviderSettlementUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderSettlementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProviderSettlementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderSettlementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderSettlementUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := providersettlement.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProviderSettlement.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderSettlementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providersettlement.Table, providersettlement.Columns, sqlgraph.NewFieldSpec(providersettlement.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderUserID(); ok {
		_spec.SetField(providersettlement.FieldProviderUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProviderUserID(); ok {
		_spec.AddField(providersettlement.FieldProviderUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(providersettlement.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PeriodEnd(); ok {
		_spec.SetField(providersettlement.FieldPeriodEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StandardCost(); ok {
		_spec.SetField(providersettlement.FieldStandardCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStandardCost(); ok {
		_spec.AddField(providersettlement.FieldStandardCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Requests(); ok {
		_spec.SetField(providersettlement.FieldRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequests(); ok {
		_spec.AddField(providersettlement.FieldRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Tokens(); ok {
		_spec.SetField(providersettlement.FieldTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTokens(); ok {
		_spec.AddField(providersettlement.FieldTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountCount(); ok {
		_spec.SetField(providersettlement.FieldAccountCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccountCount(); ok {
		_spec.AddField(providersettlement.FieldAccountCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastUsageID(); ok {
		_spec.SetField(providersettlement.FieldLastUsageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastUsageID(); ok {
		_spec.AddField(providersettlement.FieldLastUsageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(providersettlement.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(providersettlement.FieldSettledAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SettledBy(); ok {
		_spec.SetField(providersettlement.FieldSettledBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSettledBy(); ok {
		_spec.AddField(providersettlement.FieldSettledBy, field.TypeInt64, value)
	}
	if _u.mutation.SettledByCleared() {
		_spec.ClearField(providersettlement.FieldSettledBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.VoidedAt(); ok {
		_spec.SetField(providersettlement.FieldVoidedAt, field.TypeTime, value)
	}
	if _u.mutation.VoidedAtCleared() {
		_spec.ClearField(providersettlement.FieldVoidedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.VoidedBy(); ok {
		_spec.SetField(providersettlement.FieldVoidedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVoidedBy(); ok {
		_spec.AddField(providersettlement.FieldVoidedBy, field.TypeInt64, value)
	}
	if _u.mutation.VoidedByCleared() {
		_spec.ClearField(providersettlement.FieldVoidedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(providersettlement.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(providersettlement.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.VoidReason(); ok {
		_spec.SetField(providersettlement.FieldVoidReason, field.TypeString, value)
	}
	if _u.mutation.VoidReasonCleared() {
		_spec.ClearField(providersettlement.FieldVoidReason, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providersettlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProviderSettlementUpdateOne is the builder for updating a single ProviderSettlement entity.
type ProviderSettlementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProviderSettlementMutation
}

// SetProviderUserID sets the "provider_user_id" field.
func (_u *ProviderSettlementUpdateOne) SetProviderUserID(v int64) *ProviderSettlementUpdateOne {
	_u.mutation.ResetProviderUserID()
	_u.mutation.SetProviderUserID(v)
	return _u
}

// SetNillableProviderUserID sets the "provider_user_id" field if the given value is not nil.
func (_u *ProviderSettlementUpdateOne) SetNillableProviderUserID(v *int64) *ProviderSettlementUpdateOne {
	if v != nil {
		_u.SetProviderUserID(*v)
	}
	return _u
}

// AddProviderUserID adds value to the "provider_user_id" field.
func (_u *ProviderSettlementUpdateOne) AddProviderUserID(v int64) *ProviderSettlementUpdateOne {
	_u.mutation.AddProviderUserID(v)
	return _u
}

// SetPeriodStart sets the "period_start" field.
func (_u *ProviderSettlementUpdateOne) SetPeriodStart(v time.Time) *ProviderSettlementUpdateOne {
	_u.mutation.SetPeriodStart(v)
	return _u
}

// SetNillablePeriodStart sets the "period_start" field if the given value is not nil.
func (_u *ProviderSettlementUpdateOne) SetNillablePeriodStart(v *time.Time) *ProviderSettlementUpdateOne {
	if v != nil {
		_u.SetPeriodStart(*v)
	}
	return _u
}

// SetPeriodEnd sets the "period_end" field.
func (_u *ProviderSettlementUpdateOne) SetPeriodEnd(v time.Time) *ProviderSettlementUpdateOne {
	_u.mutation.SetPeriodEnd(v)
	return _u
}

// SetNillablePeriodEnd sets the "period_end" field if the given value is not nil.
func (_u *ProviderSettlementUpdateOne) SetNillablePeriodEnd(v *time.Time) *ProviderSettlementUpdateOne {
	if v != nil {
		_u.SetPeriodEnd(*v)
	}
	return _u
}

// SetStandardCost sets the "standard_cost" field.
func (_u *ProviderSettlementUpdateOne) SetStandardCost(v decimal.Decimal) *ProviderSettlementUpdateOne {
	_u.mutation.ResetStandardCost()
	_u.mutation.SetStandardCost(v)
	return _u
}

// SetNillableStandardCost sets the "standard_cost" field if the given value is not nil.
func (_u *ProviderSettlementUpdateOne) SetNillableStandardCost(v *decimal.Decimal) *ProviderSettlementUpdateOne {
	if v != nil {
		_u.SetStandardCost(*v)
	}
	return _u
}

// AddStandardCost adds value to the "standard_cost" field.
func (_u *ProviderSettlementUpdateOne) AddStandardCost(v decimal.Decimal) *ProviderSettlementUpdateOne {
	_u.mutation.AddStandardCost(v)
	return _u
}

// SetRequests sets the "requests" field.
func (_u *ProviderSettlementUpdateOne) SetRequests(v int64) *ProviderSettlementUpdateOne {
	_u.mutation.ResetRequests()
	_u.mutation.SetRequests(v)
	return _u
}

// SetNillableRequests sets the "requests" field if the given value is not nil.
func (_u *ProviderSettlementUpdateOne) SetNillableRequests(v *int64) *ProviderSettlementUpdateOne {
	if v != nil {
		_u.SetRequests(*v)
	}
	return _u
}

// AddRequests adds value to the "requests" field.
func (_u *ProviderSettlementUpdateOne) AddRequests(v int64) *ProviderSettlementUpdateOne {
	_u.mutation.AddRequests(v)
	return _u
}

// SetTokens sets the "tokens" field.
func (_u *ProviderSettlementUpdateOne) SetTokens(v int64) *ProviderSettlementUpdateOne {
	_u.mutation.ResetTokens()
	_u.mutation.SetTokens(v)
	return _u
}

// SetNillableTokens sets the "tokens" field if the given value is not nil.
func (_u *ProviderSettlementUpdateOne) SetNillableTokens(v *int64) *ProviderSettlementUpdateOne {
	if v != nil {
		_u.SetTokens(*v)
	}
	return _u
}

// AddTokens adds value to the "tokens" field.
func (_u *ProviderSettlementUpdateOne) AddTokens(v int64) *ProviderSettlementUpdateOne {
	_u.mutation.AddTokens(v)
	return _u
}

// SetAccountCount sets the "account_count" field.
func (_u *ProviderSettlementUpdateOne) SetAccountCount(v int) *ProviderSettlementUpdateOne {
	_u.mutation.ResetAccountCount()
	_u.mutation.SetAccountCount(v)
	return _u
}

// SetNillableAccountCount sets the "account_count" field if the given value is not nil.
func (_u *ProviderSettlementUpdateOne) SetNillableAccountCount(v *int) *ProviderSettlementUpdateOne {
	if v != nil {
		_u.SetAccountCount(*v)
	}
	return _u
}

// AddAccountCount adds value to the "account_count" field.
func (_u *ProviderSettlementUpdateOne) AddAccountCount(v int) *ProviderSettlementUpdateOne {
	_u.mutation.AddAccountCount(v)
	return _u
}

// SetLastUsageID sets the "last_usage_id" field.
func (_u *ProviderSettlementUpdateOne) SetLastUsageID(v int64) *ProviderSettlementUpdateOne {
	_u.mutation.ResetLastUsageID()
	_u.mutation.SetLastUsageID(v)
	return _u
}

// SetNillableLastUsageID sets the "last_usage_id" field if the given value is not nil.
func (_u *ProviderSettlementUpdateOne) SetNillableLastUsageID(v *int64) *ProviderSettlementUpdateOne {
	if v != nil {
		_u.SetLastUsageID(*v)
	}
	return _u
}

// AddLastUsageID adds value to the "last_usage_id" field.
func (_u *ProviderSettlementUpdateOne) AddLastUsageID(v int64) *ProviderSettlementUpdateOne {
	_u.mutation.AddLastUsageID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProviderSettlementUpdateOne) SetStatus(v string) *ProviderSettlementUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProviderSettlementUpdateOne) SetNillableStatus(v *string) *ProviderSettlementUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *ProviderSettlementUpdateOne) SetSettledAt(v time.Time) *ProviderSettlementUpdateOne {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *ProviderSettlementUpdateOne) SetNillableSettledAt(v *time.Time) *ProviderSettlementUpdateOne {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// SetSettledBy sets the "settled_by" field.
func (_u *ProviderSettlementUpdateOne) SetSettledBy(v int64) *ProviderSettlementUpdateOne {
	_u.mutation.ResetSettledBy()
	_u.mutation.SetSettledBy(v)
	return _u
}

// SetNillableSettledBy sets the "settled_by" field if the given value is not nil.
func (_u *ProviderSettlementUpdateOne) SetNillableSettledBy(v *int64) *ProviderSettlementUpdateOne {
	if v != nil {
		_u.SetSettledBy(*v)
	}
	return _u
}

// AddSettledBy adds value to the "settled_by" field.
func (_u *ProviderSettlementUpdateOne) AddSettledBy(v int64) *ProviderSettlementUpdateOne {
	_u.mutation.AddSettledBy(v)
	return _u
}

// ClearSettledBy clears the value of the "settled_by" field.
func (_u *ProviderSettlementUpdateOne) ClearSettledBy() *ProviderSettlementUpdateOne {
	_u.mutation.ClearSettledBy()
	return _u
}

// SetVoidedAt sets the "voided_at" field.
func (_u *ProviderSettlementUpdateOne) SetVoidedAt(v time.Time) *ProviderSettlementUpdateOne {
	_u.mutation.SetVoidedAt(v)
	return _u
}

// SetNillableVoidedAt sets the "voided_at" field if the given value is not nil.
func (_u *ProviderSettlementUpdateOne) SetNillableVoidedAt(v *time.Time) *ProviderSettlementUpdateOne {
	if v != nil {
		_u.SetVoidedAt(*v)
	}
	return _u
}

// ClearVoidedAt clears the value of the "voided_at" field.
func (_u *ProviderSettlementUpdateOne) ClearVoidedAt() *ProviderSettlementUpdateOne {
	_u.mutation.ClearVoidedAt()
	return _u
}

// SetVoidedBy sets the "voided_by" field.
func (_u *ProviderSettlementUpdateOne) SetVoidedBy(v int64) *ProviderSettlementUpdateOne {
	_u.mutation.ResetVoidedBy()
	_u.mutation.SetVoidedBy(v)
	return _u
}

// SetNillableVoidedBy sets the "voided_by" field if the given value is not nil.
func (_u *ProviderSettlementUpdateOne) SetNillableVoidedBy(v *int64) *ProviderSettlementUpdateOne {
	if v != nil {
		_u.SetVoidedBy(*v)
	}
	return _u
}

// AddVoidedBy adds value to the "voided_by" field.
func (_u *ProviderSettlementUpdateOne) AddVoidedBy(v int64) *ProviderSettlementUpdateOne {
	_u.mutation.AddVoidedBy(v)
	return _u
}

// ClearVoidedBy clears the value of the "voided_by" field.
func (_u *ProviderSettlementUpdateOne) ClearVoidedBy() *ProviderSettlementUpdateOne {
	_u.mutation.ClearVoidedBy()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ProviderSettlementUpdateOne) SetNotes(v string) *ProviderSettlementUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ProviderSettlementUpdateOne) SetNillableNotes(v *string) *ProviderSettlementUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *ProviderSettlementUpdateOne) ClearNotes() *ProviderSettlementUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetVoidReason sets the "void_reason" field.
func (_u *ProviderSettlementUpdateOne) SetVoidReason(v string) *ProviderSettlementUpdateOne {
	_u.mutation.SetVoidReason(v)
	return _u
}

// SetNillableVoidReason sets the "void_reason" field if the given value is not nil.
func (_u *ProviderSettlementUpdateOne) SetNillableVoidReason(v *string) *ProviderSettlementUpdateOne {
	if v != nil {
		_u.SetVoidReason(*v)
	}
	return _u
}

// ClearVoidReason clears the value of the "void_reason" field.
func (_u *ProviderSettlementUpdateOne) ClearVoidReason() *ProviderSettlementUpdateOne {
	_u.mutation.ClearVoidReason()
	return _u
}

// Mutation returns the ProviderSettlementMutation object of the builder.
func (_u *ProviderSettlementUpdateOne) Mutation() *ProviderSettlementMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProviderSettlementUpdate builder.
func (_u *ProviderSettlementUpdateOne) Where(ps ...predicate.ProviderSettlement) *ProviderSettlementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProviderSettlementUpdateOne) Select(field string, fields ...string) *ProviderSettlementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProviderSettlement entity.
func (_u *ProviderSettlementUpdateOne) Save(ctx context.Context) (*ProviderSettlement, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProviderSettlementUpdateOne) SaveX(ctx context.Context) *ProviderSettlement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProviderSettlementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProviderSettlementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProviderSettlementUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := providersettlement.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProviderSettlement.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ProviderSettlementUpdateOne) sqlSave(ctx context.Context) (_node *ProviderSettlement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(providersettlement.Table, providersettlement.Columns, sqlgraph.NewFieldSpec(providersettlement.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProviderSettlement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, providersettlement.FieldID)
		for _, f := range fields {
			if !providersettlement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != providersettlement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProviderUserID(); ok {
		_spec.SetField(providersettlement.FieldProviderUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProviderUserID(); ok {
		_spec.AddField(providersettlement.FieldProviderUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PeriodStart(); ok {
		_spec.SetField(providersettlement.FieldPeriodStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PeriodEnd(); ok {
		_spec.SetField(providersettlement.FieldPeriodEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StandardCost(); ok {
		_spec.SetField(providersettlement.FieldStandardCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStandardCost(); ok {
		_spec.AddField(providersettlement.FieldStandardCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Requests(); ok {
		_spec.SetField(providersettlement.FieldRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequests(); ok {
		_spec.AddField(providersettlement.FieldRequests, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Tokens(); ok {
		_spec.SetField(providersettlement.FieldTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTokens(); ok {
		_spec.AddField(providersettlement.FieldTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AccountCount(); ok {
		_spec.SetField(providersettlement.FieldAccountCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccountCount(); ok {
		_spec.AddField(providersettlement.FieldAccountCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastUsageID(); ok {
		_spec.SetField(providersettlement.FieldLastUsageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastUsageID(); ok {
		_spec.AddField(providersettlement.FieldLastUsageID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(providersettlement.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(providersettlement.FieldSettledAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SettledBy(); ok {
		_spec.SetField(providersettlement.FieldSettledBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSettledBy(); ok {
		_spec.AddField(providersettlement.FieldSettledBy, field.TypeInt64, value)
	}
	if _u.mutation.SettledByCleared() {
		_spec.ClearField(providersettlement.FieldSettledBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.VoidedAt(); ok {
		_spec.SetField(providersettlement.FieldVoidedAt, field.TypeTime, value)
	}
	if _u.mutation.VoidedAtCleared() {
		_spec.ClearField(providersettlement.FieldVoidedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.VoidedBy(); ok {
		_spec.SetField(providersettlement.FieldVoidedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVoidedBy(); ok {
		_spec.AddField(providersettlement.FieldVoidedBy, field.TypeInt64, value)
	}
	if _u.mutation.VoidedByCleared() {
		_spec.ClearField(providersettlement.FieldVoidedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(providersettlement.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(providersettlement.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.VoidReason(); ok {
		_spec.SetField(providersettlement.FieldVoidReason, field.TypeString, value)
	}
	if _u.mutation.VoidReasonCleared() {
		_spec.ClearField(providersettlement.FieldVoidReason, field.TypeString)
	}
	_node = &ProviderSettlement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{providersettlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
