// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/providersettlement"
	"github.com/shopspring/decimal"
)

// ProviderSettlementCreate is the builder for creating a ProviderSettlement entity.
type ProviderSettlementCreate struct {
	config
	mutation *ProviderSettlementMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetProviderUserID sets the "provider_user_id" field.
func (_c *ProviderSettlementCreate) SetProviderUserID(v int64) *ProviderSettlementCreate {
	_c.mutation.SetProviderUserID(v)
	return _c
}

// SetPeriodStart sets the "period_start" field.
func (_c *ProviderSettlementCreate) SetPeriodStart(v time.Time) *ProviderSettlementCreate {
	_c.mutation.SetPeriodStart(v)
	return _c
}

// SetPeriodEnd sets the "period_end" field.
func (_c *ProviderSettlementCreate) SetPeriodEnd(v time.Time) *ProviderSettlementCreate {
	_c.mutation.SetPeriodEnd(v)
	return _c
}

// SetStandardCost sets the "standard_cost" field.
func (_c *ProviderSettlementCreate) SetStandardCost(v decimal.Decimal) *ProviderSettlementCreate {
	_c.mutation.SetStandardCost(v)
	return _c
}

// SetNillableStandardCost sets the "standard_cost" field if the given value is not nil.
func (_c *ProviderSettlementCreate) SetNillableStandardCost(v *decimal.Decimal) *ProviderSettlementCreate {
	if v != nil {
		_c.SetStandardCost(*v)
	}
	return _c
}

// SetRequests sets the "requests" field.
func (_c *ProviderSettlementCreate) SetRequests(v int64) *ProviderSettlementCreate {
	_c.mutation.SetRequests(v)
	return _c
}

// SetNillableRequests sets the "requests" field if the given value is not nil.
func (_c *ProviderSettlementCreate) SetNillableRequests(v *int64) *ProviderSettlementCreate {
	if v != nil {
		_c.SetRequests(*v)
	}
	return _c
}

// SetTokens sets the "tokens" field.
func (_c *ProviderSettlementCreate) SetTokens(v int64) *ProviderSettlementCreate {
	_c.mutation.SetTokens(v)
	return _c
}

// SetNillableTokens sets the "tokens" field if the given value is not nil.
func (_c *ProviderSettlementCreate) SetNillableTokens(v *int64) *ProviderSettlementCreate {
	if v != nil {
		_c.SetTokens(*v)
	}
	return _c
}

// SetAccountCount sets the "account_count" field.
func (_c *ProviderSettlementCreate) SetAccountCount(v int) *ProviderSettlementCreate {
	_c.mutation.SetAccountCount(v)
	return _c
}

// SetNillableAccountCount sets the "account_count" field if the given value is not nil.
func (_c *ProviderSettlementCreate) SetNillableAccountCount(v *int) *ProviderSettlementCreate {
	if v != nil {
		_c.SetAccountCount(*v)
	}
	return _c
}

// SetLastUsageID sets the "last_usage_id" field.
func (_c *ProviderSettlementCreate) SetLastUsageID(v int64) *ProviderSettlementCreate {
	_c.mutation.SetLastUsageID(v)
	return _c
}

// SetNillableLastUsageID sets the "last_usage_id" field if the given value is not nil.
func (_c *ProviderSettlementCreate) SetNillableLastUsageID(v *int64) *ProviderSettlementCreate {
	if v != nil {
		_c.SetLastUsageID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ProviderSettlementCreate) SetStatus(v string) *ProviderSettlementCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ProviderSettlementCreate) SetNillableStatus(v *string) *ProviderSettlementCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSettledAt sets the "settled_at" field.
func (_c *ProviderSettlementCreate) SetSettledAt(v time.Time) *ProviderSettlementCreate {
	_c.mutation.SetSettledAt(v)
	return _c
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_c *ProviderSettlementCreate) SetNillableSettledAt(v *time.Time) *ProviderSettlementCreate {
	if v != nil {
		_c.SetSettledAt(*v)
	}
	return _c
}

// SetSettledBy sets the "settled_by" field.
func (_c *ProviderSettlementCreate) SetSettledBy(v int64) *ProviderSettlementCreate {
	_c.mutation.SetSettledBy(v)
	return _c
}

// SetNillableSettledBy sets the "settled_by" field if the given value is not nil.
func (_c *ProviderSettlementCreate) SetNillableSettledBy(v *int64) *ProviderSettlementCreate {
	if v != nil {
		_c.SetSettledBy(*v)
	}
	return _c
}

// SetVoidedAt sets the "voided_at" field.
func (_c *ProviderSettlementCreate) SetVoidedAt(v time.Time) *ProviderSettlementCreate {
	_c.mutation.SetVoidedAt(v)
	return _c
}

// SetNillableVoidedAt sets the "voided_at" field if the given value is not nil.
func (_c *ProviderSettlementCreate) SetNillableVoidedAt(v *time.Time) *ProviderSettlementCreate {
	if v != nil {
		_c.SetVoidedAt(*v)
	}
	return _c
}

// SetVoidedBy sets the "voided_by" field.
func (_c *ProviderSettlementCreate) SetVoidedBy(v int64) *ProviderSettlementCreate {
	_c.mutation.SetVoidedBy(v)
	return _c
}

// SetNillableVoidedBy sets the "voided_by" field if the given value is not nil.
func (_c *ProviderSettlementCreate) SetNillableVoidedBy(v *int64) *ProviderSettlementCreate {
	if v != nil {
		_c.SetVoidedBy(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *ProviderSettlementCreate) SetNotes(v string) *ProviderSettlementCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *ProviderSettlementCreate) SetNillableNotes(v *string) *ProviderSettlementCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetVoidReason sets the "void_reason" field.
func (_c *ProviderSettlementCreate) SetVoidReason(v string) *ProviderSettlementCreate {
	_c.mutation.SetVoidReason(v)
	return _c
}

// SetNillableVoidReason sets the "void_reason" field if the given value is not nil.
func (_c *ProviderSettlementCreate) SetNillableVoidReason(v *string) *ProviderSettlementCreate {
	if v != nil {
		_c.SetVoidReason(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProviderSettlementCreate) SetCreatedAt(v time.Time) *ProviderSettlementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProviderSettlementCreate) SetNillableCreatedAt(v *time.Time) *ProviderSettlementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ProviderSettlementMutation object of the builder.
func (_c *ProviderSettlementCreate) Mutation() *ProviderSettlementMutation {
	return _c.mutation
}

// Save creates the ProviderSettlement in the database.
func (_c *ProviderSettlementCreate) Save(ctx context.Context) (*ProviderSettlement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProviderSettlementCreate) SaveX(ctx context.Context) *ProviderSettlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderSettlementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderSettlementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProviderSettlementCreate) defaults() {
	if _, ok := _c.mutation.StandardCost(); !ok {
		v := providersettlement.DefaultStandardCost()
		_c.mutation.SetStandardCost(v)
	}
	if _, ok := _c.mutation.Requests(); !ok {
		v := providersettlement.DefaultRequests
		_c.mutation.SetRequests(v)
	}
	if _, ok := _c.mutation.Tokens(); !ok {
		v := providersettlement.DefaultTokens
		_c.mutation.SetTokens(v)
	}
	if _, ok := _c.mutation.AccountCount(); !ok {
		v := providersettlement.DefaultAccountCount
		_c.mutation.SetAccountCount(v)
	}
	if _, ok := _c.mutation.LastUsageID(); !ok {
		v := providersettlement.DefaultLastUsageID
		_c.mutation.SetLastUsageID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := providersettlement.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SettledAt(); !ok {
		v := providersettlement.DefaultSettledAt()
		_c.mutation.SetSettledAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := providersettlement.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProviderSettlementCreate) check() error {
	if _, ok := _c.mutation.ProviderUserID(); !ok {
		return &ValidationError{Name: "provider_user_id", err: errors.New(`ent: missing required field "ProviderSettlement.provider_user_id"`)}
	}
	if _, ok := _c.mutation.PeriodStart(); !ok {
		return &ValidationError{Name: "period_start", err: errors.New(`ent: missing required field "ProviderSettlement.period_start"`)}
	}
	if _, ok := _c.mutation.PeriodEnd(); !ok {
		return &ValidationError{Name: "period_end", err: errors.New(`ent: missing required field "ProviderSettlement.period_end"`)}
	}
	if _, ok := _c.mutation.StandardCost(); !ok {
		return &ValidationError{Name: "standard_cost", err: errors.New(`ent: missing required field "ProviderSettlement.standard_cost"`)}
	}
	if _, ok := _c.mutation.Requests(); !ok {
		return &ValidationError{Name: "requests", err: errors.New(`ent: missing required field "ProviderSettlement.requests"`)}
	}
	if _, ok := _c.mutation.Tokens(); !ok {
		return &ValidationError{Name: "tokens", err: errors.New(`ent: missing required field "ProviderSettlement.tokens"`)}
	}
	if _, ok := _c.mutation.AccountCount(); !ok {
		return &ValidationError{Name: "account_count", err: errors.New(`ent: missing required field "ProviderSettlement.account_count"`)}
	}
	if _, ok := _c.mutation.LastUsageID(); !ok {
		return &ValidationError{Name: "last_usage_id", err: errors.New(`ent: missing required field "ProviderSettlement.last_usage_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ProviderSettlement.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := providersettlement.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProviderSettlement.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SettledAt(); !ok {
		return &ValidationError{Name: "settled_at", err: errors.New(`ent: missing required field "ProviderSettlement.settled_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProviderSettlement.created_at"`)}
	}
	return nil
}

func (_c *ProviderSettlementCreate) sqlSave(ctx context.Context) (*ProviderSettlement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProviderSettlementCreate) createSpec() (*ProviderSettlement, *sqlgraph.CreateSpec) {
	var (
		_node = &ProviderSettlement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(providersettlement.Table, sqlgraph.NewFieldSpec(providersettlement.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ProviderUserID(); ok {
		_spec.SetField(providersettlement.FieldProviderUserID, field.TypeInt64, value)
		_node.ProviderUserID = value
	}
	if value, ok := _c.mutation.PeriodStart(); ok {
		_spec.SetField(providersettlement.FieldPeriodStart, field.TypeTime, value)
		_node.PeriodStart = value
	}
	if value, ok := _c.mutation.PeriodEnd(); ok {
		_spec.SetField(providersettlement.FieldPeriodEnd, field.TypeTime, value)
		_node.PeriodEnd = value
	}
	if value, ok := _c.mutation.StandardCost(); ok {
		_spec.SetField(providersettlement.FieldStandardCost, field.TypeFloat64, value)
		_node.StandardCost = value
	}
	if value, ok := _c.mutation.Requests(); ok {
		_spec.SetField(providersettlement.FieldRequests, field.TypeInt64, value)
		_node.Requests = value
	}
	if value, ok := _c.mutation.Tokens(); ok {
		_spec.SetField(providersettlement.FieldTokens, field.TypeInt64, value)
		_node.Tokens = value
	}
	if value, ok := _c.mutation.AccountCount(); ok {
		_spec.SetField(providersettlement.FieldAccountCount, field.TypeInt, value)
		_node.AccountCount = value
	}
	if value, ok := _c.mutation.LastUsageID(); ok {
		_spec.SetField(providersettlement.FieldLastUsageID, field.TypeInt64, value)
		_node.LastUsageID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(providersettlement.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SettledAt(); ok {
		_spec.SetField(providersettlement.FieldSettledAt, field.TypeTime, value)
		_node.SettledAt = value
	}
	if value, ok := _c.mutation.SettledBy(); ok {
		_spec.SetField(providersettlement.FieldSettledBy, field.TypeInt64, value)
		_node.SettledBy = &value
	}
	if value, ok := _c.mutation.VoidedAt(); ok {
		_spec.SetField(providersettlement.FieldVoidedAt, field.TypeTime, value)
		_node.VoidedAt = &value
	}
	if value, ok := _c.mutation.VoidedBy(); ok {
		_spec.SetField(providersettlement.FieldVoidedBy, field.TypeInt64, value)
		_node.VoidedBy = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(providersettlement.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.VoidReason(); ok {
		_spec.SetField(providersettlement.FieldVoidReason, field.TypeString, value)
		_node.VoidReason = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(providersettlement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderSettlement.Create().
//		SetProviderUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderSettlementUpsert) {
//			SetProviderUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderSettlementCreate) OnConflict(opts ...sql.ConflictOption) *ProviderSettlementUpsertOne {
	_c.conflict = opts
	return &ProviderSettlementUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderSettlement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderSettlementCreate) OnConflictColumns(columns ...string) *ProviderSettlementUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderSettlementUpsertOne{
		create: _c,
	}
}

type (
	// ProviderSettlementUpsertOne is the builder for "upsert"-ing
	//  one ProviderSettlement node.
	ProviderSettlementUpsertOne struct {
		create *ProviderSettlementCreate
	}

	// ProviderSettlementUpsert is the "OnConflict" setter.
	ProviderSettlementUpsert struct {
		*sql.UpdateSet
	}
)

// SetProviderUserID sets the "provider_user_id" field.
func (u *ProviderSettlementUpsert) SetProviderUserID(v int64) *ProviderSettlementUpsert {
	u.Set(providersettlement.FieldProviderUserID, v)
	return u
}

// UpdateProviderUserID sets the "provider_user_id" field to the value that was provided on create.
func (u *ProviderSettlementUpsert) UpdateProviderUserID() *ProviderSettlementUpsert {
	u.SetExcluded(providersettlement.FieldProviderUserID)
	return u
}

// AddProviderUserID adds v to the "provider_user_id" field.
func (u *ProviderSettlementUpsert) AddProviderUserID(v int64) *ProviderSettlementUpsert {
	u.Add(providersettlement.FieldProviderUserID, v)
	return u
}

// SetPeriodStart sets the "period_start" field.
func (u *ProviderSettlementUpsert) SetPeriodStart(v time.Time) *ProviderSettlementUpsert {
	u.Set(providersettlement.FieldPeriodStart, v)
	return u
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *ProviderSettlementUpsert) UpdatePeriodStart() *ProviderSettlementUpsert {
	u.SetExcluded(providersettlement.FieldPeriodStart)
	return u
}

// SetPeriodEnd sets the "period_end" field.
func (u *ProviderSettlementUpsert) SetPeriodEnd(v time.Time) *ProviderSettlementUpsert {
	u.Set(providersettlement.FieldPeriodEnd, v)
	return u
}

// UpdatePeriodEnd sets the "period_end" field to the value that was provided on create.
func (u *ProviderSettlementUpsert) UpdatePeriodEnd() *ProviderSettlementUpsert {
	u.SetExcluded(providersettlement.FieldPeriodEnd)
	return u
}

// SetStandardCost sets the "standard_cost" field.
func (u *ProviderSettlementUpsert) SetStandardCost(v decimal.Decimal) *ProviderSettlementUpsert {
	u.Set(providersettlement.FieldStandardCost, v)
	return u
}

// UpdateStandardCost sets the "standard_cost" field to the value that was provided on create.
func (u *ProviderSettlementUpsert) UpdateStandardCost() *ProviderSettlementUpsert {
	u.SetExcluded(providersettlement.FieldStandardCost)
	return u
}

// AddStandardCost adds v to the "standard_cost" field.
func (u *ProviderSettlementUpsert) AddStandardCost(v decimal.Decimal) *ProviderSettlementUpsert {
	u.Add(providersettlement.FieldStandardCost, v)
	return u
}

// SetRequests sets the "requests" field.
func (u *ProviderSettlementUpsert) SetRequests(v int64) *ProviderSettlementUpsert {
	u.Set(providersettlement.FieldRequests, v)
	return u
}

// UpdateRequests sets the "requests" field to the value that was provided on create.
func (u *ProviderSettlementUpsert) UpdateRequests() *ProviderSettlementUpsert {
	u.SetExcluded(providersettlement.FieldRequests)
	return u
}

// AddRequests adds v to the "requests" field.
func (u *ProviderSettlementUpsert) AddRequests(v int64) *ProviderSettlementUpsert {
	u.Add(providersettlement.FieldRequests, v)
	return u
}

// SetTokens sets the "tokens" field.
func (u *ProviderSettlementUpsert) SetTokens(v int64) *ProviderSettlementUpsert {
	u.Set(providersettlement.FieldTokens, v)
	return u
}

// UpdateTokens sets the "tokens" field to the value that was provided on create.
func (u *ProviderSettlementUpsert) UpdateTokens() *ProviderSettlementUpsert {
	u.SetExcluded(providersettlement.FieldTokens)
	return u
}

// AddTokens adds v to the "tokens" field.
func (u *ProviderSettlementUpsert) AddTokens(v int64) *ProviderSettlementUpsert {
	u.Add(providersettlement.FieldTokens, v)
	return u
}

// SetAccountCount sets the "account_count" field.
func (u *ProviderSettlementUpsert) SetAccountCount(v int) *ProviderSettlementUpsert {
	u.Set(providersettlement.FieldAccountCount, v)
	return u
}

// UpdateAccountCount sets the "account_count" field to the value that was provided on create.
func (u *ProviderSettlementUpsert) UpdateAccountCount() *ProviderSettlementUpsert {
	u.SetExcluded(providersettlement.FieldAccountCount)
	return u
}

// AddAccountCount adds v to the "account_count" field.
func (u *ProviderSettlementUpsert) AddAccountCount(v int) *ProviderSettlementUpsert {
	u.Add(providersettlement.FieldAccountCount, v)
	return u
}

// SetLastUsageID sets the "last_usage_id" field.
func (u *ProviderSettlementUpsert) SetLastUsageID(v int64) *ProviderSettlementUpsert {
	u.Set(providersettlement.FieldLastUsageID, v)
	return u
}

// UpdateLastUsageID sets the "last_usage_id" field to the value that was provided on create.
func (u *ProviderSettlementUpsert) UpdateLastUsageID() *ProviderSettlementUpsert {
	u.SetExcluded(providersettlement.FieldLastUsageID)
	return u
}

// AddLastUsageID adds v to the "last_usage_id" field.
func (u *ProviderSettlementUpsert) AddLastUsageID(v int64) *ProviderSettlementUpsert {
	u.Add(providersettlement.FieldLastUsageID, v)
	return u
}

// SetStatus sets the "status" field.
func (u *ProviderSettlementUpsert) SetStatus(v string) *ProviderSettlementUpsert {
	u.Set(providersettlement.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProviderSettlementUpsert) UpdateStatus() *ProviderSettlementUpsert {
	u.SetExcluded(providersettlement.FieldStatus)
	return u
}

// SetSettledAt sets the "settled_at" field.
func (u *ProviderSettlementUpsert) SetSettledAt(v time.Time) *ProviderSettlementUpsert {
	u.Set(providersettlement.FieldSettledAt, v)
	return u
}

// UpdateSettledAt sets the "settled_at" field to the value that was provided on create.
func (u *ProviderSettlementUpsert) UpdateSettledAt() *ProviderSettlementUpsert {
	u.SetExcluded(providersettlement.FieldSettledAt)
	return u
}

// SetSettledBy sets the "settled_by" field.
func (u *ProviderSettlementUpsert) SetSettledBy(v int64) *ProviderSettlementUpsert {
	u.Set(providersettlement.FieldSettledBy, v)
	return u
}

// UpdateSettledBy sets the "settled_by" field to the value that was provided on create.
func (u *ProviderSettlementUpsert) UpdateSettledBy() *ProviderSettlementUpsert {
	u.SetExcluded(providersettlement.FieldSettledBy)
	return u
}

// AddSettledBy adds v to the "settled_by" field.
func (u *ProviderSettlementUpsert) AddSettledBy(v int64) *ProviderSettlementUpsert {
	u.Add(providersettlement.FieldSettledBy, v)
	return u
}

// ClearSettledBy clears the value of the "settled_by" field.
func (u *ProviderSettlementUpsert) ClearSettledBy() *ProviderSettlementUpsert {
	u.SetNull(providersettlement.FieldSettledBy)
	return u
}

// SetVoidedAt sets the "voided_at" field.
func (u *ProviderSettlementUpsert) SetVoidedAt(v time.Time) *ProviderSettlementUpsert {
	u.Set(providersettlement.FieldVoidedAt, v)
	return u
}

// UpdateVoidedAt sets the "voided_at" field to the value that was provided on create.
func (u *ProviderSettlementUpsert) UpdateVoidedAt() *ProviderSettlementUpsert {
	u.SetExcluded(providersettlement.FieldVoidedAt)
	return u
}

// ClearVoidedAt clears the value of the "voided_at" field.
func (u *ProviderSettlementUpsert) ClearVoidedAt() *ProviderSettlementUpsert {
	u.SetNull(providersettlement.FieldVoidedAt)
	return u
}

// SetVoidedBy sets the "voided_by" field.
func (u *ProviderSettlementUpsert) SetVoidedBy(v int64) *ProviderSettlementUpsert {
	u.Set(providersettlement.FieldVoidedBy, v)
	return u
}

// UpdateVoidedBy sets the "voided_by" field to the value that was provided on create.
func (u *ProviderSettlementUpsert) UpdateVoidedBy() *ProviderSettlementUpsert {
	u.SetExcluded(providersettlement.FieldVoidedBy)
	return u
}

// AddVoidedBy adds v to the "voided_by" field.
func (u *ProviderSettlementUpsert) AddVoidedBy(v int64) *ProviderSettlementUpsert {
	u.Add(providersettlement.FieldVoidedBy, v)
	return u
}

// ClearVoidedBy clears the value of the "voided_by" field.
func (u *ProviderSettlementUpsert) ClearVoidedBy() *ProviderSettlementUpsert {
	u.SetNull(providersettlement.FieldVoidedBy)
	return u
}

// SetNotes sets the "notes" field.
func (u *ProviderSettlementUpsert) SetNotes(v string) *ProviderSettlementUpsert {
	u.Set(providersettlement.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ProviderSettlementUpsert) UpdateNotes() *ProviderSettlementUpsert {
	u.SetExcluded(providersettlement.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *ProviderSettlementUpsert) ClearNotes() *ProviderSettlementUpsert {
	u.SetNull(providersettlement.FieldNotes)
	return u
}

// SetVoidReason sets the "void_reason" field.
func (u *ProviderSettlementUpsert) SetVoidReason(v string) *ProviderSettlementUpsert {
	u.Set(providersettlement.FieldVoidReason, v)
	return u
}

// UpdateVoidReason sets the "void_reason" field to the value that was provided on create.
func (u *ProviderSettlementUpsert) UpdateVoidReason() *ProviderSettlementUpsert {
	u.SetExcluded(providersettlement.FieldVoidReason)
	return u
}

// ClearVoidReason clears the value of the "void_reason" field.
func (u *ProviderSettlementUpsert) ClearVoidReason() *ProviderSettlementUpsert {
	u.SetNull(providersettlement.FieldVoidReason)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProviderSettlement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProviderSettlementUpsertOne) UpdateNewValues() *ProviderSettlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(providersettlement.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderSettlement.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProviderSettlementUpsertOne) Ignore() *ProviderSettlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderSettlementUpsertOne) DoNothing() *ProviderSettlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderSettlementCreate.OnConflict
// documentation for more info.
func (u *ProviderSettlementUpsertOne) Update(set func(*ProviderSettlementUpsert)) *ProviderSettlementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderSettlementUpsert{UpdateSet: update})
	}))
	return u
}

// SetProviderUserID sets the "provider_user_id" field.
func (u *ProviderSettlementUpsertOne) SetProviderUserID(v int64) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetProviderUserID(v)
	})
}

// AddProviderUserID adds v to the "provider_user_id" field.
func (u *ProviderSettlementUpsertOne) AddProviderUserID(v int64) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.AddProviderUserID(v)
	})
}

// UpdateProviderUserID sets the "provider_user_id" field to the value that was provided on create.
func (u *ProviderSettlementUpsertOne) UpdateProviderUserID() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateProviderUserID()
	})
}

// SetPeriodStart sets the "period_start" field.
func (u *ProviderSettlementUpsertOne) SetPeriodStart(v time.Time) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetPeriodStart(v)
	})
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *ProviderSettlementUpsertOne) UpdatePeriodStart() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdatePeriodStart()
	})
}

// SetPeriodEnd sets the "period_end" field.
func (u *ProviderSettlementUpsertOne) SetPeriodEnd(v time.Time) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetPeriodEnd(v)
	})
}

// UpdatePeriodEnd sets the "period_end" field to the value that was provided on create.
func (u *ProviderSettlementUpsertOne) UpdatePeriodEnd() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdatePeriodEnd()
	})
}

// SetStandardCost sets the "standard_cost" field.
func (u *ProviderSettlementUpsertOne) SetStandardCost(v decimal.Decimal) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetStandardCost(v)
	})
}

// AddStandardCost adds v to the "standard_cost" field.
func (u *ProviderSettlementUpsertOne) AddStandardCost(v decimal.Decimal) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.AddStandardCost(v)
	})
}

// UpdateStandardCost sets the "standard_cost" field to the value that was provided on create.
func (u *ProviderSettlementUpsertOne) UpdateStandardCost() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateStandardCost()
	})
}

// SetRequests sets the "requests" field.
func (u *ProviderSettlementUpsertOne) SetRequests(v int64) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetRequests(v)
	})
}

// AddRequests adds v to the "requests" field.
func (u *ProviderSettlementUpsertOne) AddRequests(v int64) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.AddRequests(v)
	})
}

// UpdateRequests sets the "requests" field to the value that was provided on create.
func (u *ProviderSettlementUpsertOne) UpdateRequests() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateRequests()
	})
}

// SetTokens sets the "tokens" field.
func (u *ProviderSettlementUpsertOne) SetTokens(v int64) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetTokens(v)
	})
}

// AddTokens adds v to the "tokens" field.
func (u *ProviderSettlementUpsertOne) AddTokens(v int64) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.AddTokens(v)
	})
}

// UpdateTokens sets the "tokens" field to the value that was provided on create.
func (u *ProviderSettlementUpsertOne) UpdateTokens() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateTokens()
	})
}

// SetAccountCount sets the "account_count" field.
func (u *ProviderSettlementUpsertOne) SetAccountCount(v int) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetAccountCount(v)
	})
}

// AddAccountCount adds v to the "account_count" field.
func (u *ProviderSettlementUpsertOne) AddAccountCount(v int) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.AddAccountCount(v)
	})
}

// UpdateAccountCount sets the "account_count" field to the value that was provided on create.
func (u *ProviderSettlementUpsertOne) UpdateAccountCount() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateAccountCount()
	})
}

// SetLastUsageID sets the "last_usage_id" field.
func (u *ProviderSettlementUpsertOne) SetLastUsageID(v int64) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetLastUsageID(v)
	})
}

// AddLastUsageID adds v to the "last_usage_id" field.
func (u *ProviderSettlementUpsertOne) AddLastUsageID(v int64) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.AddLastUsageID(v)
	})
}

// UpdateLastUsageID sets the "last_usage_id" field to the value that was provided on create.
func (u *ProviderSettlementUpsertOne) UpdateLastUsageID() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateLastUsageID()
	})
}

// SetStatus sets the "status" field.
func (u *ProviderSettlementUpsertOne) SetStatus(v string) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProviderSettlementUpsertOne) UpdateStatus() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateStatus()
	})
}

// SetSettledAt sets the "settled_at" field.
func (u *ProviderSettlementUpsertOne) SetSettledAt(v time.Time) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetSettledAt(v)
	})
}

// UpdateSettledAt sets the "settled_at" field to the value that was provided on create.
func (u *ProviderSettlementUpsertOne) UpdateSettledAt() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateSettledAt()
	})
}

// SetSettledBy sets the "settled_by" field.
func (u *ProviderSettlementUpsertOne) SetSettledBy(v int64) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetSettledBy(v)
	})
}

// AddSettledBy adds v to the "settled_by" field.
func (u *ProviderSettlementUpsertOne) AddSettledBy(v int64) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.AddSettledBy(v)
	})
}

// UpdateSettledBy sets the "settled_by" field to the value that was provided on create.
func (u *ProviderSettlementUpsertOne) UpdateSettledBy() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateSettledBy()
	})
}

// ClearSettledBy clears the value of the "settled_by" field.
func (u *ProviderSettlementUpsertOne) ClearSettledBy() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.ClearSettledBy()
	})
}

// SetVoidedAt sets the "voided_at" field.
func (u *ProviderSettlementUpsertOne) SetVoidedAt(v time.Time) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetVoidedAt(v)
	})
}

// UpdateVoidedAt sets the "voided_at" field to the value that was provided on create.
func (u *ProviderSettlementUpsertOne) UpdateVoidedAt() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateVoidedAt()
	})
}

// ClearVoidedAt clears the value of the "voided_at" field.
func (u *ProviderSettlementUpsertOne) ClearVoidedAt() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.ClearVoidedAt()
	})
}

// SetVoidedBy sets the "voided_by" field.
func (u *ProviderSettlementUpsertOne) SetVoidedBy(v int64) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetVoidedBy(v)
	})
}

// AddVoidedBy adds v to the "voided_by" field.
func (u *ProviderSettlementUpsertOne) AddVoidedBy(v int64) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.AddVoidedBy(v)
	})
}

// UpdateVoidedBy sets the "voided_by" field to the value that was provided on create.
func (u *ProviderSettlementUpsertOne) UpdateVoidedBy() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateVoidedBy()
	})
}

// ClearVoidedBy clears the value of the "voided_by" field.
func (u *ProviderSettlementUpsertOne) ClearVoidedBy() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.ClearVoidedBy()
	})
}

// SetNotes sets the "notes" field.
func (u *ProviderSettlementUpsertOne) SetNotes(v string) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ProviderSettlementUpsertOne) UpdateNotes() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *ProviderSettlementUpsertOne) ClearNotes() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.ClearNotes()
	})
}

// SetVoidReason sets the "void_reason" field.
func (u *ProviderSettlementUpsertOne) SetVoidReason(v string) *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetVoidReason(v)
	})
}

// UpdateVoidReason sets the "void_reason" field to the value that was provided on create.
func (u *ProviderSettlementUpsertOne) UpdateVoidReason() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateVoidReason()
	})
}

// ClearVoidReason clears the value of the "void_reason" field.
func (u *ProviderSettlementUpsertOne) ClearVoidReason() *ProviderSettlementUpsertOne {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.ClearVoidReason()
	})
}

// Exec executes the query.
func (u *ProviderSettlementUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderSettlementCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderSettlementUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProviderSettlementUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProviderSettlementUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProviderSettlementCreateBulk is the builder for creating many ProviderSettlement entities in bulk.
type ProviderSettlementCreateBulk struct {
	config
	err      error
	builders []*ProviderSettlementCreate
	conflict []sql.ConflictOption
}

// Save creates the ProviderSettlement entities in the database.
func (_c *ProviderSettlementCreateBulk) Save(ctx context.Context) ([]*ProviderSettlement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProviderSettlement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProviderSettlementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProviderSettlementCreateBulk) SaveX(ctx context.Context) []*ProviderSettlement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderSettlementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderSettlementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderSettlement.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderSettlementUpsert) {
//			SetProviderUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderSettlementCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProviderSettlementUpsertBulk {
	_c.conflict = opts
	return &ProviderSettlementUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderSettlement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderSettlementCreateBulk) OnConflictColumns(columns ...string) *ProviderSettlementUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderSettlementUpsertBulk{
		create: _c,
	}
}

// ProviderSettlementUpsertBulk is the builder for "upsert"-ing
// a bulk of ProviderSettlement nodes.
type ProviderSettlementUpsertBulk struct {
	create *ProviderSettlementCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProviderSettlement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProviderSettlementUpsertBulk) UpdateNewValues() *ProviderSettlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(providersettlement.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderSettlement.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProviderSettlementUpsertBulk) Ignore() *ProviderSettlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderSettlementUpsertBulk) DoNothing() *ProviderSettlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderSettlementCreateBulk.OnConflict
// documentation for more info.
func (u *ProviderSettlementUpsertBulk) Update(set func(*ProviderSettlementUpsert)) *ProviderSettlementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderSettlementUpsert{UpdateSet: update})
	}))
	return u
}

// SetProviderUserID sets the "provider_user_id" field.
func (u *ProviderSettlementUpsertBulk) SetProviderUserID(v int64) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetProviderUserID(v)
	})
}

// AddProviderUserID adds v to the "provider_user_id" field.
func (u *ProviderSettlementUpsertBulk) AddProviderUserID(v int64) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.AddProviderUserID(v)
	})
}

// UpdateProviderUserID sets the "provider_user_id" field to the value that was provided on create.
func (u *ProviderSettlementUpsertBulk) UpdateProviderUserID() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateProviderUserID()
	})
}

// SetPeriodStart sets the "period_start" field.
func (u *ProviderSettlementUpsertBulk) SetPeriodStart(v time.Time) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetPeriodStart(v)
	})
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *ProviderSettlementUpsertBulk) UpdatePeriodStart() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdatePeriodStart()
	})
}

// SetPeriodEnd sets the "period_end" field.
func (u *ProviderSettlementUpsertBulk) SetPeriodEnd(v time.Time) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetPeriodEnd(v)
	})
}

// UpdatePeriodEnd sets the "period_end" field to the value that was provided on create.
func (u *ProviderSettlementUpsertBulk) UpdatePeriodEnd() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdatePeriodEnd()
	})
}

// SetStandardCost sets the "standard_cost" field.
func (u *ProviderSettlementUpsertBulk) SetStandardCost(v decimal.Decimal) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetStandardCost(v)
	})
}

// AddStandardCost adds v to the "standard_cost" field.
func (u *ProviderSettlementUpsertBulk) AddStandardCost(v decimal.Decimal) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.AddStandardCost(v)
	})
}

// UpdateStandardCost sets the "standard_cost" field to the value that was provided on create.
func (u *ProviderSettlementUpsertBulk) UpdateStandardCost() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateStandardCost()
	})
}

// SetRequests sets the "requests" field.
func (u *ProviderSettlementUpsertBulk) SetRequests(v int64) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetRequests(v)
	})
}

// AddRequests adds v to the "requests" field.
func (u *ProviderSettlementUpsertBulk) AddRequests(v int64) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.AddRequests(v)
	})
}

// UpdateRequests sets the "requests" field to the value that was provided on create.
func (u *ProviderSettlementUpsertBulk) UpdateRequests() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateRequests()
	})
}

// SetTokens sets the "tokens" field.
func (u *ProviderSettlementUpsertBulk) SetTokens(v int64) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetTokens(v)
	})
}

// AddTokens adds v to the "tokens" field.
func (u *ProviderSettlementUpsertBulk) AddTokens(v int64) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.AddTokens(v)
	})
}

// UpdateTokens sets the "tokens" field to the value that was provided on create.
func (u *ProviderSettlementUpsertBulk) UpdateTokens() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateTokens()
	})
}

// SetAccountCount sets the "account_count" field.
func (u *ProviderSettlementUpsertBulk) SetAccountCount(v int) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetAccountCount(v)
	})
}

// AddAccountCount adds v to the "account_count" field.
func (u *ProviderSettlementUpsertBulk) AddAccountCount(v int) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.AddAccountCount(v)
	})
}

// UpdateAccountCount sets the "account_count" field to the value that was provided on create.
func (u *ProviderSettlementUpsertBulk) UpdateAccountCount() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateAccountCount()
	})
}

// SetLastUsageID sets the "last_usage_id" field.
func (u *ProviderSettlementUpsertBulk) SetLastUsageID(v int64) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetLastUsageID(v)
	})
}

// AddLastUsageID adds v to the "last_usage_id" field.
func (u *ProviderSettlementUpsertBulk) AddLastUsageID(v int64) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.AddLastUsageID(v)
	})
}

// UpdateLastUsageID sets the "last_usage_id" field to the value that was provided on create.
func (u *ProviderSettlementUpsertBulk) UpdateLastUsageID() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateLastUsageID()
	})
}

// SetStatus sets the "status" field.
func (u *ProviderSettlementUpsertBulk) SetStatus(v string) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ProviderSettlementUpsertBulk) UpdateStatus() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateStatus()
	})
}

// SetSettledAt sets the "settled_at" field.
func (u *ProviderSettlementUpsertBulk) SetSettledAt(v time.Time) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetSettledAt(v)
	})
}

// UpdateSettledAt sets the "settled_at" field to the value that was provided on create.
func (u *ProviderSettlementUpsertBulk) UpdateSettledAt() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateSettledAt()
	})
}

// SetSettledBy sets the "settled_by" field.
func (u *ProviderSettlementUpsertBulk) SetSettledBy(v int64) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetSettledBy(v)
	})
}

// AddSettledBy adds v to the "settled_by" field.
func (u *ProviderSettlementUpsertBulk) AddSettledBy(v int64) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.AddSettledBy(v)
	})
}

// UpdateSettledBy sets the "settled_by" field to the value that was provided on create.
func (u *ProviderSettlementUpsertBulk) UpdateSettledBy() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateSettledBy()
	})
}

// ClearSettledBy clears the value of the "settled_by" field.
func (u *ProviderSettlementUpsertBulk) ClearSettledBy() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.ClearSettledBy()
	})
}

// SetVoidedAt sets the "voided_at" field.
func (u *ProviderSettlementUpsertBulk) SetVoidedAt(v time.Time) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetVoidedAt(v)
	})
}

// UpdateVoidedAt sets the "voided_at" field to the value that was provided on create.
func (u *ProviderSettlementUpsertBulk) UpdateVoidedAt() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateVoidedAt()
	})
}

// ClearVoidedAt clears the value of the "voided_at" field.
func (u *ProviderSettlementUpsertBulk) ClearVoidedAt() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.ClearVoidedAt()
	})
}

// SetVoidedBy sets the "voided_by" field.
func (u *ProviderSettlementUpsertBulk) SetVoidedBy(v int64) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetVoidedBy(v)
	})
}

// AddVoidedBy adds v to the "voided_by" field.
func (u *ProviderSettlementUpsertBulk) AddVoidedBy(v int64) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.AddVoidedBy(v)
	})
}

// UpdateVoidedBy sets the "voided_by" field to the value that was provided on create.
func (u *ProviderSettlementUpsertBulk) UpdateVoidedBy() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateVoidedBy()
	})
}

// ClearVoidedBy clears the value of the "voided_by" field.
func (u *ProviderSettlementUpsertBulk) ClearVoidedBy() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.ClearVoidedBy()
	})
}

// SetNotes sets the "notes" field.
func (u *ProviderSettlementUpsertBulk) SetNotes(v string) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *ProviderSettlementUpsertBulk) UpdateNotes() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *ProviderSettlementUpsertBulk) ClearNotes() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.ClearNotes()
	})
}

// SetVoidReason sets the "void_reason" field.
func (u *ProviderSettlementUpsertBulk) SetVoidReason(v string) *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.SetVoidReason(v)
	})
}

// UpdateVoidReason sets the "void_reason" field to the value that was provided on create.
func (u *ProviderSettlementUpsertBulk) UpdateVoidReason() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.UpdateVoidReason()
	})
}

// ClearVoidReason clears the value of the "void_reason" field.
func (u *ProviderSettlementUpsertBulk) ClearVoidReason() *ProviderSettlementUpsertBulk {
	return u.Update(func(s *ProviderSettlementUpsert) {
		s.ClearVoidReason()
	})
}

// Exec executes the query.
func (u *ProviderSettlementUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProviderSettlementCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderSettlementCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderSettlementUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
