// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/providersettlementitem"
	"github.com/shopspring/decimal"
)

// ProviderSettlementItemCreate is the builder for creating a ProviderSettlementItem entity.
type ProviderSettlementItemCreate struct {
	config
	mutation *ProviderSettlementItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSettlementID sets the "settlement_id" field.
func (_c *ProviderSettlementItemCreate) SetSettlementID(v int64) *ProviderSettlementItemCreate {
	_c.mutation.SetSettlementID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *ProviderSettlementItemCreate) SetAccountID(v int64) *ProviderSettlementItemCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetAccountName sets the "account_name" field.
func (_c *ProviderSettlementItemCreate) SetAccountName(v string) *ProviderSettlementItemCreate {
	_c.mutation.SetAccountName(v)
	return _c
}

// SetNillableAccountName sets the "account_name" field if the given value is not nil.
func (_c *ProviderSettlementItemCreate) SetNillableAccountName(v *string) *ProviderSettlementItemCreate {
	if v != nil {
		_c.SetAccountName(*v)
	}
	return _c
}

// SetOffline sets the "offline" field.
func (_c *ProviderSettlementItemCreate) SetOffline(v bool) *ProviderSettlementItemCreate {
	_c.mutation.SetOffline(v)
	return _c
}

// SetNillableOffline sets the "offline" field if the given value is not nil.
func (_c *ProviderSettlementItemCreate) SetNillableOffline(v *bool) *ProviderSettlementItemCreate {
	if v != nil {
		_c.SetOffline(*v)
	}
	return _c
}

// SetRequests sets the "requests" field.
func (_c *ProviderSettlementItemCreate) SetRequests(v int64) *ProviderSettlementItemCreate {
	_c.mutation.SetRequests(v)
	return _c
}

// SetNillableRequests sets the "requests" field if the given value is not nil.
func (_c *ProviderSettlementItemCreate) SetNillableRequests(v *int64) *ProviderSettlementItemCreate {
	if v != nil {
		_c.SetRequests(*v)
	}
	return _c
}

// SetTokens sets the "tokens" field.
func (_c *ProviderSettlementItemCreate) SetTokens(v int64) *ProviderSettlementItemCreate {
	_c.mutation.SetTokens(v)
	return _c
}

// SetNillableTokens sets the "tokens" field if the given value is not nil.
func (_c *ProviderSettlementItemCreate) SetNillableTokens(v *int64) *ProviderSettlementItemCreate {
	if v != nil {
		_c.SetTokens(*v)
	}
	return _c
}

// SetStandardCost sets the "standard_cost" field.
func (_c *ProviderSettlementItemCreate) SetStandardCost(v decimal.Decimal) *ProviderSettlementItemCreate {
	_c.mutation.SetStandardCost(v)
	return _c
}

// SetNillableStandardCost sets the "standard_cost" field if the given value is not nil.
func (_c *ProviderSettlementItemCreate) SetNillableStandardCost(v *decimal.Decimal) *ProviderSettlementItemCreate {
	if v != nil {
		_c.SetStandardCost(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ProviderSettlementItemCreate) SetCreatedAt(v time.Time) *ProviderSettlementItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ProviderSettlementItemCreate) SetNillableCreatedAt(v *time.Time) *ProviderSettlementItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ProviderSettlementItemMutation object of the builder.
func (_c *ProviderSettlementItemCreate) Mutation() *ProviderSettlementItemMutation {
	return _c.mutation
}

// Save creates the ProviderSettlementItem in the database.
func (_c *ProviderSettlementItemCreate) Save(ctx context.Context) (*ProviderSettlementItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ProviderSettlementItemCreate) SaveX(ctx context.Context) *ProviderSettlementItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderSettlementItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderSettlementItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ProviderSettlementItemCreate) defaults() {
	if _, ok := _c.mutation.AccountName(); !ok {
		v := providersettlementitem.DefaultAccountName
		_c.mutation.SetAccountName(v)
	}
	if _, ok := _c.mutation.Offline(); !ok {
		v := providersettlementitem.DefaultOffline
		_c.mutation.SetOffline(v)
	}
	if _, ok := _c.mutation.Requests(); !ok {
		v := providersettlementitem.DefaultRequests
		_c.mutation.SetRequests(v)
	}
	if _, ok := _c.mutation.Tokens(); !ok {
		v := providersettlementitem.DefaultTokens
		_c.mutation.SetTokens(v)
	}
	if _, ok := _c.mutation.StandardCost(); !ok {
		v := providersettlementitem.DefaultStandardCost()
		_c.mutation.SetStandardCost(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := providersettlementitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ProviderSettlementItemCreate) check() error {
	if _, ok := _c.mutation.SettlementID(); !ok {
		return &ValidationError{Name: "settlement_id", err: errors.New(`ent: missing required field "ProviderSettlementItem.settlement_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "ProviderSettlementItem.account_id"`)}
	}
	if _, ok := _c.mutation.AccountName(); !ok {
		return &ValidationError{Name: "account_name", err: errors.New(`ent: missing required field "ProviderSettlementItem.account_name"`)}
	}
	if v, ok := _c.mutation.AccountName(); ok {
		if err := providersettlementitem.AccountNameValidator(v); err != nil {
			return &ValidationError{Name: "account_name", err: fmt.Errorf(`ent: validator failed for field "ProviderSettlementItem.account_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Offline(); !ok {
		return &ValidationError{Name: "offline", err: errors.New(`ent: missing required field "ProviderSettlementItem.offline"`)}
	}
	if _, ok := _c.mutation.Requests(); !ok {
		return &ValidationError{Name: "requests", err: errors.New(`ent: missing required field "ProviderSettlementItem.requests"`)}
	}
	if _, ok := _c.mutation.Tokens(); !ok {
		return &ValidationError{Name: "tokens", err: errors.New(`ent: missing required field "ProviderSettlementItem.tokens"`)}
	}
	if _, ok := _c.mutation.StandardCost(); !ok {
		return &ValidationError{Name: "standard_cost", err: errors.New(`ent: missing required field "ProviderSettlementItem.standard_cost"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProviderSettlementItem.created_at"`)}
	}
	return nil
}

func (_c *ProviderSettlementItemCreate) sqlSave(ctx context.Context) (*ProviderSettlementItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ProviderSettlementItemCreate) createSpec() (*ProviderSettlementItem, *sqlgraph.CreateSpec) {
	var (
		_node = &ProviderSettlementItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(providersettlementitem.Table, sqlgraph.NewFieldSpec(providersettlementitem.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.SettlementID(); ok {
		_spec.SetField(providersettlementitem.FieldSettlementID, field.TypeInt64, value)
		_node.SettlementID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(providersettlementitem.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.AccountName(); ok {
		_spec.SetField(providersettlementitem.FieldAccountName, field.TypeString, value)
		_node.AccountName = value
	}
	if value, ok := _c.mutation.Offline(); ok {
		_spec.SetField(providersettlementitem.FieldOffline, field.TypeBool, value)
		_node.Offline = value
	}
	if value, ok := _c.mutation.Requests(); ok {
		_spec.SetField(providersettlementitem.FieldRequests, field.TypeInt64, value)
		_node.Requests = value
	}
	if value, ok := _c.mutation.Tokens(); ok {
		_spec.SetField(providersettlementitem.FieldTokens, field.TypeInt64, value)
		_node.Tokens = value
	}
	if value, ok := _c.mutation.StandardCost(); ok {
		_spec.SetField(providersettlementitem.FieldStandardCost, field.TypeFloat64, value)
		_node.StandardCost = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(providersettlementitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderSettlementItem.Create().
//		SetSettlementID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderSettlementItemUpsert) {
//			SetSettlementID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderSettlementItemCreate) OnConflict(opts ...sql.ConflictOption) *ProviderSettlementItemUpsertOne {
	_c.conflict = opts
	return &ProviderSettlementItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderSettlementItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderSettlementItemCreate) OnConflictColumns(columns ...string) *ProviderSettlementItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderSettlementItemUpsertOne{
		create: _c,
	}
}

type (
	// ProviderSettlementItemUpsertOne is the builder for "upsert"-ing
	//  one ProviderSettlementItem node.
	ProviderSettlementItemUpsertOne struct {
		create *ProviderSettlementItemCreate
	}

	// ProviderSettlementItemUpsert is the "OnConflict" setter.
	ProviderSettlementItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetSettlementID sets the "settlement_id" field.
func (u *ProviderSettlementItemUpsert) SetSettlementID(v int64) *ProviderSettlementItemUpsert {
	u.Set(providersettlementitem.FieldSettlementID, v)
	return u
}

// UpdateSettlementID sets the "settlement_id" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsert) UpdateSettlementID() *ProviderSettlementItemUpsert {
	u.SetExcluded(providersettlementitem.FieldSettlementID)
	return u
}

// AddSettlementID adds v to the "settlement_id" field.
func (u *ProviderSettlementItemUpsert) AddSettlementID(v int64) *ProviderSettlementItemUpsert {
	u.Add(providersettlementitem.FieldSettlementID, v)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *ProviderSettlementItemUpsert) SetAccountID(v int64) *ProviderSettlementItemUpsert {
	u.Set(providersettlementitem.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsert) UpdateAccountID() *ProviderSettlementItemUpsert {
	u.SetExcluded(providersettlementitem.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *ProviderSettlementItemUpsert) AddAccountID(v int64) *ProviderSettlementItemUpsert {
	u.Add(providersettlementitem.FieldAccountID, v)
	return u
}

// SetAccountName sets the "account_name" field.
func (u *ProviderSettlementItemUpsert) SetAccountName(v string) *ProviderSettlementItemUpsert {
	u.Set(providersettlementitem.FieldAccountName, v)
	return u
}

// UpdateAccountName sets the "account_name" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsert) UpdateAccountName() *ProviderSettlementItemUpsert {
	u.SetExcluded(providersettlementitem.FieldAccountName)
	return u
}

// SetOffline sets the "offline" field.
func (u *ProviderSettlementItemUpsert) SetOffline(v bool) *ProviderSettlementItemUpsert {
	u.Set(providersettlementitem.FieldOffline, v)
	return u
}

// UpdateOffline sets the "offline" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsert) UpdateOffline() *ProviderSettlementItemUpsert {
	u.SetExcluded(providersettlementitem.FieldOffline)
	return u
}

// SetRequests sets the "requests" field.
func (u *ProviderSettlementItemUpsert) SetRequests(v int64) *ProviderSettlementItemUpsert {
	u.Set(providersettlementitem.FieldRequests, v)
	return u
}

// UpdateRequests sets the "requests" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsert) UpdateRequests() *ProviderSettlementItemUpsert {
	u.SetExcluded(providersettlementitem.FieldRequests)
	return u
}

// AddRequests adds v to the "requests" field.
func (u *ProviderSettlementItemUpsert) AddRequests(v int64) *ProviderSettlementItemUpsert {
	u.Add(providersettlementitem.FieldRequests, v)
	return u
}

// SetTokens sets the "tokens" field.
func (u *ProviderSettlementItemUpsert) SetTokens(v int64) *ProviderSettlementItemUpsert {
	u.Set(providersettlementitem.FieldTokens, v)
	return u
}

// UpdateTokens sets the "tokens" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsert) UpdateTokens() *ProviderSettlementItemUpsert {
	u.SetExcluded(providersettlementitem.FieldTokens)
	return u
}

// AddTokens adds v to the "tokens" field.
func (u *ProviderSettlementItemUpsert) AddTokens(v int64) *ProviderSettlementItemUpsert {
	u.Add(providersettlementitem.FieldTokens, v)
	return u
}

// SetStandardCost sets the "standard_cost" field.
func (u *ProviderSettlementItemUpsert) SetStandardCost(v decimal.Decimal) *ProviderSettlementItemUpsert {
	u.Set(providersettlementitem.FieldStandardCost, v)
	return u
}

// UpdateStandardCost sets the "standard_cost" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsert) UpdateStandardCost() *ProviderSettlementItemUpsert {
	u.SetExcluded(providersettlementitem.FieldStandardCost)
	return u
}

// AddStandardCost adds v to the "standard_cost" field.
func (u *ProviderSettlementItemUpsert) AddStandardCost(v decimal.Decimal) *ProviderSettlementItemUpsert {
	u.Add(providersettlementitem.FieldStandardCost, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ProviderSettlementItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProviderSettlementItemUpsertOne) UpdateNewValues() *ProviderSettlementItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(providersettlementitem.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderSettlementItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ProviderSettlementItemUpsertOne) Ignore() *ProviderSettlementItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderSettlementItemUpsertOne) DoNothing() *ProviderSettlementItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderSettlementItemCreate.OnConflict
// documentation for more info.
func (u *ProviderSettlementItemUpsertOne) Update(set func(*ProviderSettlementItemUpsert)) *ProviderSettlementItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderSettlementItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetSettlementID sets the "settlement_id" field.
func (u *ProviderSettlementItemUpsertOne) SetSettlementID(v int64) *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.SetSettlementID(v)
	})
}

// AddSettlementID adds v to the "settlement_id" field.
func (u *ProviderSettlementItemUpsertOne) AddSettlementID(v int64) *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.AddSettlementID(v)
	})
}

// UpdateSettlementID sets the "settlement_id" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsertOne) UpdateSettlementID() *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.UpdateSettlementID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ProviderSettlementItemUpsertOne) SetAccountID(v int64) *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *ProviderSettlementItemUpsertOne) AddAccountID(v int64) *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsertOne) UpdateAccountID() *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.UpdateAccountID()
	})
}

// SetAccountName sets the "account_name" field.
func (u *ProviderSettlementItemUpsertOne) SetAccountName(v string) *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.SetAccountName(v)
	})
}

// UpdateAccountName sets the "account_name" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsertOne) UpdateAccountName() *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.UpdateAccountName()
	})
}

// SetOffline sets the "offline" field.
func (u *ProviderSettlementItemUpsertOne) SetOffline(v bool) *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.SetOffline(v)
	})
}

// UpdateOffline sets the "offline" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsertOne) UpdateOffline() *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.UpdateOffline()
	})
}

// SetRequests sets the "requests" field.
func (u *ProviderSettlementItemUpsertOne) SetRequests(v int64) *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.SetRequests(v)
	})
}

// AddRequests adds v to the "requests" field.
func (u *ProviderSettlementItemUpsertOne) AddRequests(v int64) *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.AddRequests(v)
	})
}

// UpdateRequests sets the "requests" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsertOne) UpdateRequests() *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.UpdateRequests()
	})
}

// SetTokens sets the "tokens" field.
func (u *ProviderSettlementItemUpsertOne) SetTokens(v int64) *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.SetTokens(v)
	})
}

// AddTokens adds v to the "tokens" field.
func (u *ProviderSettlementItemUpsertOne) AddTokens(v int64) *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.AddTokens(v)
	})
}

// UpdateTokens sets the "tokens" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsertOne) UpdateTokens() *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.UpdateTokens()
	})
}

// SetStandardCost sets the "standard_cost" field.
func (u *ProviderSettlementItemUpsertOne) SetStandardCost(v decimal.Decimal) *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.SetStandardCost(v)
	})
}

// AddStandardCost adds v to the "standard_cost" field.
func (u *ProviderSettlementItemUpsertOne) AddStandardCost(v decimal.Decimal) *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.AddStandardCost(v)
	})
}

// UpdateStandardCost sets the "standard_cost" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsertOne) UpdateStandardCost() *ProviderSettlementItemUpsertOne {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.UpdateStandardCost()
	})
}

// Exec executes the query.
func (u *ProviderSettlementItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderSettlementItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderSettlementItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ProviderSettlementItemUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ProviderSettlementItemUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ProviderSettlementItemCreateBulk is the builder for creating many ProviderSettlementItem entities in bulk.
type ProviderSettlementItemCreateBulk struct {
	config
	err      error
	builders []*ProviderSettlementItemCreate
	conflict []sql.ConflictOption
}

// Save creates the ProviderSettlementItem entities in the database.
func (_c *ProviderSettlementItemCreateBulk) Save(ctx context.Context) ([]*ProviderSettlementItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ProviderSettlementItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProviderSettlementItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ProviderSettlementItemCreateBulk) SaveX(ctx context.Context) []*ProviderSettlementItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ProviderSettlementItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ProviderSettlementItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ProviderSettlementItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ProviderSettlementItemUpsert) {
//			SetSettlementID(v+v).
//		}).
//		Exec(ctx)
func (_c *ProviderSettlementItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *ProviderSettlementItemUpsertBulk {
	_c.conflict = opts
	return &ProviderSettlementItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ProviderSettlementItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ProviderSettlementItemCreateBulk) OnConflictColumns(columns ...string) *ProviderSettlementItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ProviderSettlementItemUpsertBulk{
		create: _c,
	}
}

// ProviderSettlementItemUpsertBulk is the builder for "upsert"-ing
// a bulk of ProviderSettlementItem nodes.
type ProviderSettlementItemUpsertBulk struct {
	create *ProviderSettlementItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ProviderSettlementItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ProviderSettlementItemUpsertBulk) UpdateNewValues() *ProviderSettlementItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(providersettlementitem.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ProviderSettlementItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ProviderSettlementItemUpsertBulk) Ignore() *ProviderSettlementItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ProviderSettlementItemUpsertBulk) DoNothing() *ProviderSettlementItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ProviderSettlementItemCreateBulk.OnConflict
// documentation for more info.
func (u *ProviderSettlementItemUpsertBulk) Update(set func(*ProviderSettlementItemUpsert)) *ProviderSettlementItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ProviderSettlementItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetSettlementID sets the "settlement_id" field.
func (u *ProviderSettlementItemUpsertBulk) SetSettlementID(v int64) *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.SetSettlementID(v)
	})
}

// AddSettlementID adds v to the "settlement_id" field.
func (u *ProviderSettlementItemUpsertBulk) AddSettlementID(v int64) *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.AddSettlementID(v)
	})
}

// UpdateSettlementID sets the "settlement_id" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsertBulk) UpdateSettlementID() *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.UpdateSettlementID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ProviderSettlementItemUpsertBulk) SetAccountID(v int64) *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *ProviderSettlementItemUpsertBulk) AddAccountID(v int64) *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsertBulk) UpdateAccountID() *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.UpdateAccountID()
	})
}

// SetAccountName sets the "account_name" field.
func (u *ProviderSettlementItemUpsertBulk) SetAccountName(v string) *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.SetAccountName(v)
	})
}

// UpdateAccountName sets the "account_name" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsertBulk) UpdateAccountName() *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.UpdateAccountName()
	})
}

// SetOffline sets the "offline" field.
func (u *ProviderSettlementItemUpsertBulk) SetOffline(v bool) *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.SetOffline(v)
	})
}

// UpdateOffline sets the "offline" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsertBulk) UpdateOffline() *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.UpdateOffline()
	})
}

// SetRequests sets the "requests" field.
func (u *ProviderSettlementItemUpsertBulk) SetRequests(v int64) *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.SetRequests(v)
	})
}

// AddRequests adds v to the "requests" field.
func (u *ProviderSettlementItemUpsertBulk) AddRequests(v int64) *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.AddRequests(v)
	})
}

// UpdateRequests sets the "requests" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsertBulk) UpdateRequests() *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.UpdateRequests()
	})
}

// SetTokens sets the "tokens" field.
func (u *ProviderSettlementItemUpsertBulk) SetTokens(v int64) *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.SetTokens(v)
	})
}

// AddTokens adds v to the "tokens" field.
func (u *ProviderSettlementItemUpsertBulk) AddTokens(v int64) *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.AddTokens(v)
	})
}

// UpdateTokens sets the "tokens" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsertBulk) UpdateTokens() *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.UpdateTokens()
	})
}

// SetStandardCost sets the "standard_cost" field.
func (u *ProviderSettlementItemUpsertBulk) SetStandardCost(v decimal.Decimal) *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.SetStandardCost(v)
	})
}

// AddStandardCost adds v to the "standard_cost" field.
func (u *ProviderSettlementItemUpsertBulk) AddStandardCost(v decimal.Decimal) *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.AddStandardCost(v)
	})
}

// UpdateStandardCost sets the "standard_cost" field to the value that was provided on create.
func (u *ProviderSettlementItemUpsertBulk) UpdateStandardCost() *ProviderSettlementItemUpsertBulk {
	return u.Update(func(s *ProviderSettlementItemUpsert) {
		s.UpdateStandardCost()
	})
}

// Exec executes the query.
func (u *ProviderSettlementItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ProviderSettlementItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ProviderSettlementItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ProviderSettlementItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
