// Code generated by ent, DO NOT EDIT.

package providersettlementitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
)

const (
	// Label holds the string label denoting the providersettlementitem type in the database.
	Label = "provider_settlement_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSettlementID holds the string denoting the settlement_id field in the database.
	FieldSettlementID = "settlement_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldAccountName holds the string denoting the account_name field in the database.
	FieldAccountName = "account_name"
	// FieldOffline holds the string denoting the offline field in the database.
	FieldOffline = "offline"
	// FieldRequests holds the string denoting the requests field in the database.
	FieldRequests = "requests"
	// FieldTokens holds the string denoting the tokens field in the database.
	FieldTokens = "tokens"
	// FieldStandardCost holds the string denoting the standard_cost field in the database.
	FieldStandardCost = "standard_cost"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the providersettlementitem in the database.
	Table = "provider_settlement_items"
)

// Columns holds all SQL columns for providersettlementitem fields.
var Columns = []string{
	FieldID,
	FieldSettlementID,
	FieldAccountID,
	FieldAccountName,
	FieldOffline,
	FieldRequests,
	FieldTokens,
	FieldStandardCost,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultAccountName holds the default value on creation for the "account_name" field.
	DefaultAccountName string
	// AccountNameValidator is a validator for the "account_name" field. It is called by the builders before save.
	AccountNameValidator func(string) error
	// DefaultOffline holds the default value on creation for the "offline" field.
	DefaultOffline bool
	// DefaultRequests holds the default value on creation for the "requests" field.
	DefaultRequests int64
	// DefaultTokens holds the default value on creation for the "tokens" field.
	DefaultTokens int64
	// DefaultStandardCost holds the default value on creation for the "standard_cost" field.
	DefaultStandardCost func() decimal.Decimal
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ProviderSettlementItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySettlementID orders the results by the settlement_id field.
func BySettlementID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettlementID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByAccountName orders the results by the account_name field.
func ByAccountName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountName, opts...).ToFunc()
}

// ByOffline orders the results by the offline field.
func ByOffline(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOffline, opts...).ToFunc()
}

// ByRequests orders the results by the requests field.
func ByRequests(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequests, opts...).ToFunc()
}

// ByTokens orders the results by the tokens field.
func ByTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokens, opts...).ToFunc()
}

// ByStandardCost orders the results by the standard_cost field.
func ByStandardCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStandardCost, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
