// Code generated by ent, DO NOT EDIT.

package providersettlementitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldLTE(FieldID, id))
}

// SettlementID applies equality check predicate on the "settlement_id" field. It's identical to SettlementIDEQ.
func SettlementID(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEQ(FieldSettlementID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEQ(FieldAccountID, v))
}

// AccountName applies equality check predicate on the "account_name" field. It's identical to AccountNameEQ.
func AccountName(v string) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEQ(FieldAccountName, v))
}

// Offline applies equality check predicate on the "offline" field. It's identical to OfflineEQ.
func Offline(v bool) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEQ(FieldOffline, v))
}

// Requests applies equality check predicate on the "requests" field. It's identical to RequestsEQ.
func Requests(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEQ(FieldRequests, v))
}

// Tokens applies equality check predicate on the "tokens" field. It's identical to TokensEQ.
func Tokens(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEQ(FieldTokens, v))
}

// StandardCost applies equality check predicate on the "standard_cost" field. It's identical to StandardCostEQ.
func StandardCost(v decimal.Decimal) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEQ(FieldStandardCost, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEQ(FieldCreatedAt, v))
}

// SettlementIDEQ applies the EQ predicate on the "settlement_id" field.
func SettlementIDEQ(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEQ(FieldSettlementID, v))
}

// SettlementIDNEQ applies the NEQ predicate on the "settlement_id" field.
func SettlementIDNEQ(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldNEQ(FieldSettlementID, v))
}

// SettlementIDIn applies the In predicate on the "settlement_id" field.
func SettlementIDIn(vs ...int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldIn(FieldSettlementID, vs...))
}

// SettlementIDNotIn applies the NotIn predicate on the "settlement_id" field.
func SettlementIDNotIn(vs ...int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldNotIn(FieldSettlementID, vs...))
}

// SettlementIDGT applies the GT predicate on the "settlement_id" field.
func SettlementIDGT(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldGT(FieldSettlementID, v))
}

// SettlementIDGTE applies the GTE predicate on the "settlement_id" field.
func SettlementIDGTE(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldGTE(FieldSettlementID, v))
}

// SettlementIDLT applies the LT predicate on the "settlement_id" field.
func SettlementIDLT(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldLT(FieldSettlementID, v))
}

// SettlementIDLTE applies the LTE predicate on the "settlement_id" field.
func SettlementIDLTE(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldLTE(FieldSettlementID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldLTE(FieldAccountID, v))
}

// AccountNameEQ applies the EQ predicate on the "account_name" field.
func AccountNameEQ(v string) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEQ(FieldAccountName, v))
}

// AccountNameNEQ applies the NEQ predicate on the "account_name" field.
func AccountNameNEQ(v string) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldNEQ(FieldAccountName, v))
}

// AccountNameIn applies the In predicate on the "account_name" field.
func AccountNameIn(vs ...string) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldIn(FieldAccountName, vs...))
}

// AccountNameNotIn applies the NotIn predicate on the "account_name" field.
func AccountNameNotIn(vs ...string) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldNotIn(FieldAccountName, vs...))
}

// AccountNameGT applies the GT predicate on the "account_name" field.
func AccountNameGT(v string) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldGT(FieldAccountName, v))
}

// AccountNameGTE applies the GTE predicate on the "account_name" field.
func AccountNameGTE(v string) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldGTE(FieldAccountName, v))
}

// AccountNameLT applies the LT predicate on the "account_name" field.
func AccountNameLT(v string) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldLT(FieldAccountName, v))
}

// AccountNameLTE applies the LTE predicate on the "account_name" field.
func AccountNameLTE(v string) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldLTE(FieldAccountName, v))
}

// AccountNameContains applies the Contains predicate on the "account_name" field.
func AccountNameContains(v string) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldContains(FieldAccountName, v))
}

// AccountNameHasPrefix applies the HasPrefix predicate on the "account_name" field.
func AccountNameHasPrefix(v string) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldHasPrefix(FieldAccountName, v))
}

// AccountNameHasSuffix applies the HasSuffix predicate on the "account_name" field.
func AccountNameHasSuffix(v string) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldHasSuffix(FieldAccountName, v))
}

// AccountNameEqualFold applies the EqualFold predicate on the "account_name" field.
func AccountNameEqualFold(v string) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEqualFold(FieldAccountName, v))
}

// AccountNameContainsFold applies the ContainsFold predicate on the "account_name" field.
func AccountNameContainsFold(v string) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldContainsFold(FieldAccountName, v))
}

// OfflineEQ applies the EQ predicate on the "offline" field.
func OfflineEQ(v bool) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEQ(FieldOffline, v))
}

// OfflineNEQ applies the NEQ predicate on the "offline" field.
func OfflineNEQ(v bool) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldNEQ(FieldOffline, v))
}

// RequestsEQ applies the EQ predicate on the "requests" field.
func RequestsEQ(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEQ(FieldRequests, v))
}

// RequestsNEQ applies the NEQ predicate on the "requests" field.
func RequestsNEQ(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldNEQ(FieldRequests, v))
}

// RequestsIn applies the In predicate on the "requests" field.
func RequestsIn(vs ...int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldIn(FieldRequests, vs...))
}

// RequestsNotIn applies the NotIn predicate on the "requests" field.
func RequestsNotIn(vs ...int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldNotIn(FieldRequests, vs...))
}

// RequestsGT applies the GT predicate on the "requests" field.
func RequestsGT(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldGT(FieldRequests, v))
}

// RequestsGTE applies the GTE predicate on the "requests" field.
func RequestsGTE(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldGTE(FieldRequests, v))
}

// RequestsLT applies the LT predicate on the "requests" field.
func RequestsLT(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldLT(FieldRequests, v))
}

// RequestsLTE applies the LTE predicate on the "requests" field.
func RequestsLTE(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldLTE(FieldRequests, v))
}

// TokensEQ applies the EQ predicate on the "tokens" field.
func TokensEQ(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEQ(FieldTokens, v))
}

// TokensNEQ applies the NEQ predicate on the "tokens" field.
func TokensNEQ(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldNEQ(FieldTokens, v))
}

// TokensIn applies the In predicate on the "tokens" field.
func TokensIn(vs ...int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldIn(FieldTokens, vs...))
}

// TokensNotIn applies the NotIn predicate on the "tokens" field.
func TokensNotIn(vs ...int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldNotIn(FieldTokens, vs...))
}

// TokensGT applies the GT predicate on the "tokens" field.
func TokensGT(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldGT(FieldTokens, v))
}

// TokensGTE applies the GTE predicate on the "tokens" field.
func TokensGTE(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldGTE(FieldTokens, v))
}

// TokensLT applies the LT predicate on the "tokens" field.
func TokensLT(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldLT(FieldTokens, v))
}

// TokensLTE applies the LTE predicate on the "tokens" field.
func TokensLTE(v int64) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldLTE(FieldTokens, v))
}

// StandardCostEQ applies the EQ predicate on the "standard_cost" field.
func StandardCostEQ(v decimal.Decimal) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEQ(FieldStandardCost, v))
}

// StandardCostNEQ applies the NEQ predicate on the "standard_cost" field.
func StandardCostNEQ(v decimal.Decimal) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldNEQ(FieldStandardCost, v))
}

// StandardCostIn applies the In predicate on the "standard_cost" field.
func StandardCostIn(vs ...decimal.Decimal) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldIn(FieldStandardCost, vs...))
}

// StandardCostNotIn applies the NotIn predicate on the "standard_cost" field.
func StandardCostNotIn(vs ...decimal.Decimal) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldNotIn(FieldStandardCost, vs...))
}

// StandardCostGT applies the GT predicate on the "standard_cost" field.
func StandardCostGT(v decimal.Decimal) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldGT(FieldStandardCost, v))
}

// StandardCostGTE applies the GTE predicate on the "standard_cost" field.
func StandardCostGTE(v decimal.Decimal) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldGTE(FieldStandardCost, v))
}

// StandardCostLT applies the LT predicate on the "standard_cost" field.
func StandardCostLT(v decimal.Decimal) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldLT(FieldStandardCost, v))
}

// StandardCostLTE applies the LTE predicate on the "standard_cost" field.
func StandardCostLTE(v decimal.Decimal) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldLTE(FieldStandardCost, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProviderSettlementItem) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProviderSettlementItem) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProviderSettlementItem) predicate.ProviderSettlementItem {
	return predicate.ProviderSettlementItem(sql.NotPredicates(p))
}
